type: object
title: spotinst:azure:compute:group
properties:
  id:
    type: string
    example: "sbgd-9876"
  status:
    type: string
    example: "ROLL_STARTING"
  currentBatch:
    type: integer
    readOnly: true
    example: 1
    description: >
      Batch number that is currenlty being deployed
  numOfBatches:
    type: integer
    readOnly: true
    example: 2
    description: >
      Total number of batches the deployment will process
  progress:
    type: object
    readOnly: true
    properties:
      unit:
        type: string
        example: percentage
      value:
        type: integer
        example: 10
  groupId:
    type: string
    example: "sig-12345"
    readOnly: true
    description: >
      The Azure Elastigroup the deployment is executing on