type: array
description: |
  Configure load balancer settings for the VNG.
items:
  $ref: "./ocean-lb.yaml"
example:
  - type: CLASSIC
    name: "MyClassicLoadBalancer"
  - type: TARGET_GROUP
    arn: "arn:aws:elasticloadbalancing:us-west-2:922761411234:targetgroup"

#    todo guy - decide if to keep or change other places in cluster requests