type: object
description: GPU configuration
properties:
  sharing:
    type: array
    maximum: 1
    description: |
      List of configurations for GPU sharing. You can get up to 1 configuration.
    items:
      type: object
      properties:
        gpuSharingType:
          type: string
          enum:
            - timeSlicing
          description: |
            Type of GPU sharing.
          example: "timeSlicing"
        config:
          type: object
          properties:
            replicas:
              minimum: 1
              type: integer
              description: |
                Number of shared replicas for the GPU sharing configuration.
              example: 2
example:
  sharing:
    - gpuSharingType: "timeSlicing"
      config:
        replicas: 2