post:
  summary: "Elastigroup Azure - Vms - Create Deployment"
  description: >
    Deploy the Elastigroup. This triggers a Blue/Green deployment that replaces the existing VMs in the Elastigroup.
  operationId: "elastigroupAzureSpotVmsCreateDeployment"
  tags:
    - "Elastigroup Azure"
  parameters:
    - $ref: "../../../../commons/parameters/accountId.yaml"
    - $ref: "../../commons/parameters/groupId.yaml"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - type: "object"
              properties:
                deployment:
                  type: object
                  required:
                    - batchSizePercentage
                  properties:
                    batchSizePercentage:
                      type: integer
                      example: 50
                      description: >
                        Indicates (in percentage) the batch size of the deployment (meaning, how many nodes to replace in each batch). Valid values: 1-100. Cannot be null.
                        Default: 25
                    gracePeriod:
                      type: integer
                      example: 300
                      description: >
                        Indicates (in seconds) the timeout to wait until the node becomes healthy. Must be at least 300.
                        Default: 600
                    batchMinHealthyPercentage:
                      type: integer
                      example: 100
                      description: >
                        Indicates the threshold of minimum healthy virtual machines in a single batch. If the amount of healthy virtual machines in a single batch is under the threshold, the deployment will fail. If exists, the parameter value will be in the range of 1-100. In case of null as value, the default value in the backend will be 50%. The value of the parameter should represent the number in percentage (%) of the batch.
                        Default: 50
                    drainingTimeout:
                      type: integer
                      example: 120
                      description: >
                        Indicates (in seconds) the timeout to drain the instances. Minimum 0. Can be null.
                        Default: The Elastigroups draining time out or 120.
                    healthCheckTypes:
                      type: string
                      example: vmState
                      description: >
                        Define a health check type. Valid values: "vmState", "applicationGateway". Can be null. If no value is set, the deployment will use the group’s auto-healing health check.
  responses:
    200:
      $ref: "../responses/groupVmDeployment.yaml"
    400:
      description: "Bad Request"

get:
  summary: "Elastigroup Azure - Vms - List Group Deployments"
  description: >
    Deploy the Elastigroup. This triggers a Blue/Green deployment that replaces the existing VMs in the Elastigroup.
  operationId: "elastigroupAzureSpotVmsListGroupDeployment"
  tags:
    - "Elastigroup Azure"
  parameters:
    - $ref: "../../../../commons/parameters/accountId.yaml"
    - $ref: "../../commons/parameters/groupId.yaml"
    - in: query
      name: LIMIT
      example: 14
      description: >
        Limits the number of deployments returned.
        Default: 5
      schema:
        type: integer
    - in: query
      name: SORT
      example: createdAt:DESC
      description: >
        Field by which to sort the results.
        Default: createdAt:DESC
      schema:
        type: string
  responses:
    200:
      $ref: "../responses/groupVmDeployment.yaml"
    400:
      description: "Bad Request"

