description: |
  List of issues associated with a Spark application
content:
  application/json:
    schema:
      allOf:
        - $ref: ../schemas/responseItemWrapper.yaml
        - type: object
          properties:
            response:
              type: object
              description: |
                response body
              properties:
                items:
                  type: array
                  items:
                    $ref: ../schemas/oceanSparkIssues.yaml
