description: A paginated list of Spark application
content:
  application/json:
    schema:
      allOf:
        - $ref: ../schemas/responseItemWrapper.yaml
        - type: object
          properties:
            response:
              type: object
              description: |
                response body
              properties:
                items:
                  type: array
                  items:
                    allOf:
                      - $ref: ../schemas/paginatedList.yaml
                      - type: object
                        properties:
                          page:
                            type: array
                            items:
                              $ref: ../schemas/oceanSparkApplicationPageItem.yaml
