openapi: "3.0.0"
info:
  description: "Spotinst Elastigroup - Azure"
  version: "1.0.0"
  title: "Spotinst Elastigroup - Azure"
  contact:
    email: "support@spotinst.com"
servers:
- url: https://api.spotinst.io/compute/azure
schemes:
- "https"
security:
  - BearerAuth: []
tags:
- name: "Elastigroup Azure"
  description: "Elastigroup for Azure"
paths:
  /group:
    $ref: 'paths/groups.yaml'
  /group/{groupId}:
    $ref: 'paths/group.yaml'
  /group/{groupId}/status:
    $ref: 'paths/group-status.yaml'
  /group/{groupId}/detachInstances:
    $ref: 'paths/group-detach.yaml'
  /group/{groupId}/roll:
    $ref: 'paths/group-deployments.yaml'
  /group/{groupId}/roll/{rollId}:
    $ref: 'paths/group-deployment.yaml'
  /task:
    $ref: 'paths/tasks.yaml'
  /task/{taskId}:
    $ref: 'paths/task.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../../commons/security.yaml#/components/securitySchemes/BearerAuth'
