description: Elastigroup Response
content:
  application/json:
    schema:
      allOf:
        - $ref: "../../../../../commons/schemas/responseItemWrapper.yaml"
        - type: "object"
          properties:
            response:
              type: "object"
              properties:
                items:
                  type: "array"
                  items:
                    $ref: "../schemas/groupVmDeploymentDetails.yaml"
                kind:
                  example: spotinst:azure:compute:deployment:details
