type: object
properties:
  id:
    type: string
    title: ID
    example: sbgd-3ee19606
  status:
    type: in_progress
    title: Status
    example: STARTING
  currentBatch:
    type: integer
    title: Status
    example: 1
  numOfBatches:
    type: integer
    title: Status
    example: 1
  progress:
    type: object
    properties:
      unit:
        type: string
        title: Unit
        example: percent
      value:
        type: integer
        title: Value
        example: 0