type: object
properties:
  batchSizePercentage:
    type: integer
    title: Batch size percentage indicator
    description: >
      Indicates (in percentage) the batch size of the deployment (meaning, how many instances to replace in each batch)
    example: 20
  gracePeriod:
    type: integer
    title: Grace period indicator
    example: 300
    description: >
      Indicates (in seconds) the timeout to wait until instance become healthy based on the healthCheckType
  healthCheckType:
    type: string
    title: Health check type indicator
    description: >
      Define a health check type. valid values: ELB, ECS_CLUSTER_INSTANCE, TARGET_GROUP, OPSWORKS, NOMAD_NODE, MULTAI_TARGET_SET, HCS, EC2, NONE (wait the entire grace period for each batch). If no value is set the roll will use the group’s auto-healing health check.
    example: EC2
  strategy:
    type: object
    title: Strategy
    description: >
      The roll strategy
    properties:
      action:
        type: string
        title: Action indicator
        description: >
          The roll action to perform. valid values: REPLACE_SERVER, RESTART_SERVER
        default: REPLACE_SERVER
        example: REPLACE_SERVER
      batchMinHealthyPercentage:
        type: integer
        title: Batch min healthy percentage indicator
        description: >
          Indicates the threshold of minimum healthy instances in single batch. If the amount of healthy instances in single batch is under the threshold, the deployment will fail. If exists, the parameter value will be in range of 0-100. In case of null as value, the default value in the backend will be 50%. Value of param should represent the number in percentage (%) of the batch.
        default: 50
        example: 25
      onFailure:
        type: object
        title: On Failure
        description: >
          Set detach options to the deployment
        properties:
          actionType:
            type: string
            title: Action Type Indicator
            description: >
              Sets the action that will take place, Accepted values are: DETACH_OLD, DETACH_NEW
            example: DETACH_NEW
          shouldHandleAllBatches:
            type: boolean
            title: Should Handle ALl Batches Crieria
            description: >
              Indicator if the action should apply to all batches of the deployment or only the latest batch
            default: false
            example: true
          drainingTimeout:
            type: integer
            title: Draining Timeout Indicator
            description: >
              Indicates (in seconds) the timeout to drain the instances
            default: The Elastigroups draining time out
            example: 600
          shouldDecrementTargetCapacity:
            type: boolean
            title: Should Decrement Target Capacity
            description: >
              Decrementing the group target capacity after detaching the instances
            default: true
            example: true