type: object
title: Metric config
required:
  - name
  - metricName
  - namespace
properties:
  name:
    type: string
    description: |
      The metric name.
    example: "metric1"
  metricName:
    type: string
    description: |
      The name of the source metric.
    example: "CPUUtilization"
  namespace:
    type: string
    description: |
      The namespace for the alarm's associated metric.
    default: "AWS/EC2"
  statistic:
    type: string
    description: |
      The metric statistics to return.
    enum: [ average , sum , sampleCount , maximum , minimum , percentile ]
    example: "average"
  extendedStatistic:
    type: string
    description: |
      Percentile statistic. Valid values: p0.1 - p100.
    example: "p1.5"
  unit:
    type: string
    description: |
      The unit for the alarm's associated metric.
    enum: [ seconds , microseconds , milliseconds , bytes , kilobytes , megabytes , gigabytes , terabytes , bits , kilobits , megabits , gigabits , terabits , percent , count , bytes/second , kilobytes/second , megabytes/second , gigabytes/second , terabytes/second , bits/second , kilobits/second , megabits/second , gigabits/second , terabits/second , count/second , none ]
    example: "percent"
  dimensions:
    type: array
    description: |
      The dimensions for the alarm's associated metric.
      When name is "instanceId", no value is needed.
    items:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "InstanceId"
        value:
          type: string

