get:
  summary: Get Deployment
  description: |
    Get the status of a specific deployment.
  operationId: elastigroupAzureSpotVmsDeploymentStatus
  tags:
    - Elastigroup Azure Spot VMs
  parameters:
    - $ref: ../components/parameters/accountId.yaml
    - $ref: ../components/parameters/groupId.yaml
    - in: path
      name: deploymentId
      example: sbgd-9876
      description: |
        The deployment ID you want to query.
      schema:
        type: string
      required: true
  responses:
    '200':
      $ref: ../components/responses/groupVmDeployment.yaml
    '400':
      description: Bad Request
