get:
  summary: Import Group From Application Gateway
  description: >
    Given an application gateway, constructs a valid group configuration and
    returns it.
  operationId: elastigroupAzureSpotVmsImportFromApplicationGateway
  tags:
    - Elastigroup Azure Spot VMs
  parameters:
    - $ref: ../components/parameters/accountId.yaml
    - in: path
      name: resourceGroupName
      example: ExampleResourceGroup
      schema:
        type: string
      required: true
    - in: path
      name: applicationGatewayName
      example: MyExampleApplicationGatewayImport
      schema:
        type: string
      required: true
    - in: path
      name: backendPoolName
      example: MyExampleBackendPoolName
      schema:
        type: string
      required: true
  responses:
    '200':
      $ref: ../components/responses/importFromApplicationGateway.yaml
    '400':
      description: Bad Request
