get:
  summary: Get Stateful Node from an Azure VM
  description: >
    Get the configuration of a stateful node that was built from an Azure VM.
    This configuration is used for the [Import VM to a Stateful Node
    API](https://docs.spot.io/api/#operation/azureStatefulNodeImportVm).
  operationId: azureStatefulNodeGetImportConfiguration
  tags:
    - Elastigroup Azure Stateful
  parameters:
    - $ref: ../components/parameters/accountId.yaml
    - in: path
      name: resourceGroupName
      example: importResourceGroup
      description: |
        Name of the Resource Group of the imported VM.
      schema:
        type: string
      required: true
    - in: path
      name: virtualMachineName
      example: spot-12345678-vm
      description: |
        Name of the imported VM.
      schema:
        type: string
      required: true
  responses:
    '200':
      $ref: ../components/responses/createStatefulNode.yaml
    '400':
      description: Bad Request
