summary: Ocean Spark
get:
  summary: List Config Templates in Cluster
  description: |
    List the config templates tied to a specific cluster.
  operationId: OceanSparkClusterConfigTemplateList
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
  responses:
    '200':
      $ref: ../components/responses/configTemplates.yaml
    '400':
      description: Bad Request
post:
  summary: Create Config Template
  description: |
    Create a new configuration template
  operationId: OceanSparkClusterConfigTemplateCreate
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          required:
            - id
            - config
          properties:
            id:
              $ref: ../components/schemas/oceanSparkConfigTemplateId.yaml
            displayName:
              $ref: ../components/schemas/oceanSparkConfigTemplateDisplayName.yaml
            config:
              description: |
                The piece of configuration contained in the config template.
              allOf:
                - $ref: ../components/schemas/oceanSparkApplicationSpec.yaml
  responses:
    '200':
      $ref: ../components/responses/configTemplates.yaml
    '400':
      description: Bad Request
