summary: Ocean Spark
get:
  summary: Get Application
  description: |
    Describe a Spark application in an Ocean Spark cluster.
  operationId: OceanSparkClusterApplicationGet
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkApplicationId.yaml
  responses:
    '200':
      $ref: ../components/responses/detailedApplication.yaml
    '400':
      description: Bad Request
delete:
  summary: Delete or kill an Application
  description: >
    For pending Spark applications, the creation request is canceled. For
    running Spark applications, the application is forcibly interrupted.
  operationId: OceanSparkClusterApplicationDelete
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkApplicationId.yaml
  responses:
    '200':
      $ref: ../components/responses/killedApplication.yaml
    '400':
      description: Bad Request
