summary: Ocean Spark
get:
  summary: Stream Driver log
  description: |
    Stream the driver log of a Spark application in real time.
  operationId: OceanSparkClusterApplicationLogsLive
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkApplicationId.yaml
  responses:
    '200':
      $ref: ../components/responses/logsLive.yaml
    '400':
      description: Bad Request
