summary: Ocean Spark
get:
  summary: List Config Templates
  description: |
    List config templates across all clusters.
  operationId: OceanSparkConfigTemplateList
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
  responses:
    '200':
      $ref: ../components/responses/configTemplates.yaml
    '400':
      description: Bad Request
