summary: Ocean Spark
get:
  summary: Get Config Template
  description: |
    Describe a config template tied to an Ocean Spark cluster.
  operationId: OceanSparkClusterConfigTemplateGet
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkConfigTemplateId.yaml
  responses:
    '200':
      $ref: ../components/responses/configTemplates.yaml
    '400':
      description: Bad Request
put:
  summary: Put Config Template
  description: >
    Update a config template by replacing the existing configuration with the
    one provided in the request body.
  operationId: OceanSparkClusterConfigTemplatePut
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkConfigTemplateId.yaml
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            displayName:
              $ref: ../components/schemas/oceanSparkConfigTemplateDisplayName.yaml
            config:
              description: >
                The piece of configuration that will replace the existing
                configuration
              allOf:
                - $ref: ../components/schemas/oceanSparkApplicationSpec.yaml
  responses:
    '200':
      $ref: ../components/responses/configTemplates.yaml
    '400':
      description: Bad Request
delete:
  summary: Delete Config Template
  description: |
    Delete a config template.
  operationId: OceanSparkClusterConfigTemplateDelete
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkConfigTemplateId.yaml
  responses:
    '204':
      description: Config Template Deleted
    '400':
      description: Bad Request
