summary: Ocean Spark
get:
  summary: Download Executor logs
  description: |
    Download an archive of the executor logs for a finished spark application.
  operationId: OceanSparkClusterApplicationExecutorLogsArchive
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkApplicationId.yaml
  responses:
    '200':
      $ref: ../components/responses/executorLogsArchive.yaml
    '400':
      description: Bad Request
