put:
  summary: Put Job Config Template
  description: >
    Attach or update an attached config template by replacing the existing
    configuration with the one provided in the request body.
  operationId: OceanSparkJobConfig
  tags:
    - Ocean Spark
  parameters:
    - $ref: ../components/parameters/nonRequiredAccountId.yaml
    - $ref: ../components/parameters/oceanSparkClusterId.yaml
    - $ref: ../components/parameters/oceanSparkJobId-2.yaml
  requestBody:
    required: false
    content:
      application/json:
        schema:
          type: object
          properties:
            config:
              description: >
                The piece of configuration that will replace the existing
                configuration, if empty then the job configuration will be
                removed
              allOf:
                - $ref: ../components/schemas/oceanSparkApplicationSpec.yaml
  responses:
    '200':
      $ref: ../components/responses/jobUpdate.yaml
    '400':
      description: Bad Request
