# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
api/spot.yaml:
  info-license:
    - '#/info'
  tag-description:
    - '#/tags/17/description'
    - '#/tags/18/description'
    - '#/tags/20/description'
  no-ambiguous-paths:
    - '#/paths/~1aws~1ec2~1managedInstance~1migration~1{MIGRATION_ID}'
api/services/ocean/spark/schemas/oceanSparkApplicationSpec.yaml:
  spec:
    - '#/components'

