# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
api/spot.yaml:
  info-license:
    - '#/info'
  tag-description:
    - '#/tags/17/description'
    - '#/tags/18/description'
    - '#/tags/20/description'
  no-ambiguous-paths:
    - '#/paths/~1aws~1ec2~1managedInstance~1migration~1{MIGRATION_ID}'
api/commons/parameters/fromDateUnixEnabled.yaml:
  spec:
    - '#/components'
api/commons/parameters/toDateUnixEnabled.yaml:
  spec:
    - '#/components'
api/commons/parameters/nonRequiredFromDateUnixEnabled.yaml:
  spec:
    - '#/components'
api/commons/parameters/nonRequiredToDateUnixEnabled.yaml:
  spec:
    - '#/components'
api/services/ocean/spark/schemas/oceanSparkApplicationSpec.yaml:
  spec:
    - '#/components'
api/services/administration/general/paths/organizationInstancesCosts.yaml:
  no-invalid-media-type-examples:
    - '#/post/responses/200/content/application~1csv/example'

