type: object
description: >
  The Configuration for scheduling automatic upgrades of your cluster to ensure it stays updated with the latest version.
title: Upgrade Config
properties:
  applyRoll:
    type: boolean
    description: >
      When set to True, a cluster roll will be initiated if a new version is available to upgrade in the dedicated virtual node groups.
    example: 20
  scopeVersion:
    type: string
    description: >
      The scope of the upgrade version.
    enum:
      - patch
  rollParameters:
    type: object
    description: >
      The parameters of the cluster roll that will be initiated.
    properties:
      batchSizePercentage:
        type: integer
        minimum: 1
        maximum: 100
        description: >
          The percentage of the cluster that will be rolled at each batch.
        example: 20
      comment:
        type: string
        description: >
          A comment to be added to the cluster roll.
        example: Scheduled cluster roll
      respectPdb:
        type: boolean
        description: >
          During the roll, if the parameter is set to true we honor PDB during the instance replacement.
        example: true
      respectRestrictScaleDown:
        type: boolean
        description: >
          During the roll, if the parameter is set to true we honor Restrict Scale Down label during the nodes replacement.
        example: true
      batchMinHealthyPercentage:
        type: integer
        minimum: 1
        maximum: 100
        description: >
          The minimum percentage of the scaled nodes that should be healthy at each batch.
        example: 80