type: object
description: >
  The object specifying the Ocean Spark Log Collection configuration.
properties:
  collectDriverLogs:
    type: boolean
    default: true
    example: false
    description: |
      Enable/Disable collecting driver logs