description: >
  The current state of the Spark application.


  Transient states:

  * `PENDING`: The spark-submit operation was successful.
  The Spark driver pod is now pending: the k8s cluster must find room for it and download its Docker image.

  * `RUNNING`: The Spark driver pod starts running. It will now execute your application code.


  Terminal states:

  * `COMPLETED`: The application completed successfully.

  * `COMPLETED_WITH_WARNINGS`: The application completed, but some non-fatal errors were found in the Spark Event Log.

  * `FAILED`: The application exited with a non-zero exit code.
  
  * `KILLED`: The application was manually killed before completion.
  
  * `TIMED_OUT`: The application was programmatically killed before completion because it was either pending or running longer than the timeout defined.
example: "RUNNING"
enum:
- PENDING
- RUNNING
- COMPLETED
- COMPLETED_WITH_WARNINGS
- FAILED
- KILLED
- TIMED_OUT
