type: object
description: >
  The object specifying the Ocean Spark Log Collection configuration.
properties:
  collectAppLogs:
    type: boolean
    default: true
    example: false
    description: |
      Enable/Disable collecting driver and executor logs. When enabled, logs are stored by NetApp and can be downloaded from 
      the Spot console web interface. The logs are deleted after 30 days.