type: object
description: >
  The object specifying the Ocean Spark Workspaces configuration.
properties:
  storageClassOverride:
    allOf:
    - $ref: "k8sName.yaml"
    - example: my-custom-storage-class
      description: |
        The storage class to use for Ocean Spark workspaces. If not set, the cluster's default storage class will 
        be used.