type: object
description: >
  The object specifying the Ocean Spark Log Collection configuration.
properties:
  collectDriverLogs:
    type: boolean
    default: true
    example: false
    description: |
      Enable/Disable collecting driver logs. When enabled, driver logs are stored by NetApp and can be downloaded from 
      the Spot console web interface. The driver logs are deleted after 30 days.