description: >
  The current state of the Spark application.


  Transient states:

  * `NEW`: The application creation request was received. The spark-submit operation is pending.

  * `SUBMITTED`: The spark-submit operation was successful.
  The Spark driver pod is now pending: the k8s cluster must find room for it and download its Docker image.

  * `RUNNING`: The Spark driver pod starts running. It will now execute your application code.


  Terminal states:

  * `COMPLETED`: The application completed successfully.

  * `FAILED`: The application exited with a non-zero exit code.

  * `SUBMISSION_FAILED`: The Spark application could not be started
  because the spark-submit operation failed.
example: "RUNNING"
enum:
- NEW
- SUBMITTED
- RUNNING
- COMPLETED
- FAILED
- SUBMISSION_FAILED
- UNKNOWN
