get:
  summary: "Elastigroup Azure - Deployment Status Details"
  description: >
    Get the detailed status of a specific deployment. This includes status details per batch and other information.
  operationId: "elastigroupAzureSpotVmsDeploymentStatusDetails"
  tags:
    - Elastigroup Azure Spot VMs Deployment
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../../../commons/parameters/groupId.yaml"
    - in: query
      name: DEPLOYMENT_ID
      example: sbgd-9876
      description: >
        The deployment ID you want to query.
      schema:
        type: string
      required: true
  responses:
    200:
      $ref: "../responses/groupVmDeploymentDetails.yaml"
    400:
      description: "Bad Request"

