type: object
title: Ocean CD Spot Deployment Selector
description: >
  Used to match the rolloutspec to a `SpotDeployment` resource.
  You must specify either `SpotDeployment` OR `SpotDeployments` but not both.
  In case you are using `SpotDeployment`, `traffic` manager is optional.
properties:
  clusterId:
    type: string
    description: Existing Ocean CD cluster identifier where the matching `SpotDeployment` exists
  namespace:
    type: string
    description: Should equal the namespace where the matching `SpotDeployment` exists
  name:
    type: string
    description: The name of the `SpotDeployment` resource
required:
  - clusterId
  - namespace
  - name