type: object
title: Ocean CD Workload Migration SpotDeployment Status
description: >
  Contains Workload's Migration SpotDeployment Status.
properties:
  observedGeneration:
    type: integer
  replicas:
    type: integer
  updatedReplicas:
    type: integer
  readyReplicas:
    type: integer
  availableReplicas:
    type: integer
  unavailableReplicas:
    type: integer
  conditions:
    type: array
    items:
      type: object
      properties:
        lastTransitionTime:
          type: string
        lastUpdateTime:
          type: string
        message:
          type: string
        reason:
          type: string
        status:
          type: string
        type:
          type: string
        additionalProperties:
          type: object
  collisionCount:
    type: integer
  revision:
    type: integer
  liveVersionDate:
    type: string
    example: "2018-11-05T12:55:50.000+0000"
  liveVersionImages:
    type: object
    additionalProperties:
      type: string
  phase:
    type: string