type: object
title: Ocean CD Rollout Spec Trafic ALB Stickiness config
description: >
  Allows to specify further settings on the ForwaredConfig
properties:
  enabled:
    type: boolean
  durationSeconds:
    type: integer