type: object
title: Ocean CD Rollout Spec Traffic ALB Stickiness config
description: >
  Allows to specify further settings on the ForwardConfig
properties:
  enabled:
    type: boolean
    example: true
  durationSeconds:
    type: integer
    example: 3600