type: object
title: Ocean CD Rollout SpotDeployment Base
description: The associated SpotDeployment's info
properties:
  name:
    type: string
    description: The name of the associated SpotDeployment
    example: example-12345
  isLiveApplied:
    type: boolean
    description: Indicates whether the applied version is the same that currently running
    example: false
  revision:
    type: integer
    description: The field specifying the SpotDeployment revision rollback to
    example: 3
  $ref: "oceanCDRolloutSpotDeploymentManifestsAndVersions.yaml"