type: object
properties:
  id:
    type: string
    example: sbgd-f331fb8e
  groupId:
    type: string
    example: sig-a7aa60cd
  status:
    type: string
    example: deploymentStart
  currentBatch:
    type: integer
    example: 1
  numOfBatches:
    type: integer
    example: 2
  progress:
    type: object
    properties:
      unit:
        type: string
        example: percentage
      value:
        type: integer
        example: 10
  updatedAt:
    type: string
    example: 2020-06-22T11:15:06.614Z
  createdAt:
    type: string
    example: 2020-06-22T11:15:06.614Z

