type: object
properties:
  detailsOverview:
    type: object
    properties:
      deploymentId:
        type: string
        example: sbgd-04c4658b
      numberOfBatches:
        type: integer
        example: 2
      currentBatch:
        type: integer
        example: 2
      gracePeriod:
        type: integer
        example: 2
      blueVms:
        type: integer
        example: 2
      greenVms:
        type: integer
        example: 1
      description:
        type: string
        example: null
      errorMessage:
        type: string
        example: null
      createdAt:
        type: string
        example: 2020-06-18T05:33:18.000Z
      healthCheck:
        type: array
        items:
          type: string
          example: instanceState
  batches:
    type: array
    items:
      type: object
      properties:
        batch:
          type: integer
          example: 1
        blue:
          type: object
          properties:
            vmName:
              type: string
              example: i-57ef3cf7a694
            batchNum:
              type: integer
              example: 1
            status:
              type: string
              example: detached
            type:
              type: string
              example: old
            updatedAt:
              type: string
              example: 2020-06-18T11:16:58.000Z
        green:
          type: object
          properties:
            vmName:
              type: string
              example: i-f2a44ba41875
            batchNum:
              type: integer
              example: 1
            status:
              type: string
              example: detached
            type:
              type: string
              example: old
            updatedAt:
              type: string
              example: 2020-06-18T11:16:58.000Z
  events:
    type: array
    items:
      type: object
      properties:
        status:
          type: string
          example: deploymentStart
        eventType:
          type: string
          example: Batch 1 - Launching New instances
        timestamp:
          type: string
          example: 2020-06-18T05:33:18.000Z

