description: "Ocean Rightsizing Recommendation Application History Response"
content:
  application/json:
    schema:
      allOf:
        - $ref: "../../../../commons/schemas/responseItemWrapper.yaml"
        - type: object
          properties:
            request:
              type: object
              properties:
                url:
                  example: "/ocean/o-abcd1234/rightSizing/namespaces/kube-system/deployment/redis-controller/recommendation-application-history"
                method:
                  example: "GET"
            response:
              type: object
              properties:
                kind:
                  example: "mcs:ocean:rightSizing:recommendationApplicationHistory"
                items:
                  type: array
                  items:
                    $ref: "../schemas/oceanRightsizingRecommendationApplicationHistory.yaml"
                  example:
                    - page:
                        - containerName: "my-app-container"
                          actionType: "APPLIED"
                          currentResources:
                            cpu: 4000
                            memory: 16000
                          recommendedResources:
                            cpu: 2000
                            memory: 8000
                          occurredAt: 1776178797289
                          ruleName: "my-app-rule"
                count:
                  example: 1

