description: Ocean Rightsizing Cluster Configuration Response
content:
  application/json:
    schema:
      allOf:
        - $ref: "../../../../commons/schemas/responseItemWrapper.yaml"
        - type: object
          properties:
            request:
              type: object
              properties:
                url:
                  example: "/ocean/{oceanId}/rightSizing/cluster/configuration"
                method:
                  example: "POST"
            response:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      oceanId:
                        type: string
                        example: "o-abcd1234"
                      clusterIdentifier:
                        type: string
                        example: "dev-cluster"
                      config:
                        type: object
                        properties:
                          recommendationsCpuPercentile:
                            type: integer
                            example: 85
                          recommendationsMemoryPercentile:
                            type: integer
                            example: 85
                          recommendationsMemoryPercentile:
                            type: integer
                            example: 85
                kind:
                  example: "mcs:ocean:rightSizing:clusterConfiguration"