get:
  summary: "Get Workload Recommendation Application History"
  description: |
    Returns a set of recommendation application history records associated with workload.
  operationId: "getWorkloadRecommendationApplicationHistory"
  tags:
    - "Ocean Automatic Rightsizing"
  parameters:
    - $ref: "../parameters/oceanId.yaml"
    - $ref: "../parameters/namespace.yaml"
    - $ref: "../parameters/workloadType.yaml"
    - $ref: "../parameters/workloadName.yaml"
    - $ref: "../../../../commons/parameters/accountId.yaml"
    - $ref: "../parameters/offset.yaml"
    - $ref: "../parameters/limit.yaml"
  responses:
    200:
      $ref: "../responses/oceanRightsizingRecommendationApplicationHistoryResponse.yaml"
    400:
      description: "Invalid request provided"
    404:
      description: "Non existent resource has been queried"
    422:
      description: "Business rule violated"

