post:
  summary: "Set Cluster Recommendations Percentile"
  description: |
    Set Recommendations Percentile for the Ocean Cluster.
    <br />
    <br />
    **This action can take a few minutes to complete.**
  operationId: "SetClusterRecommendationsPercentile"
  tags:
    - "Ocean Automatic Rightsizing"
  parameters:
    - $ref: "../parameters/oceanId.yaml"
    - $ref: "../parameters/clusterIdentifier.yaml"
    - $ref: "../../../../commons/parameters/accountId.yaml"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/oceanRightsizingSetClusterRecommendationsPercentileRequest.yaml"
  responses:
    200:
      description: Ocean Cluster Recommendations Percentile Response
      $ref: "../responses/oceanRightsizingClusterConfigurationResponse.yaml"
    400:
      description: "Bad Request"