properties:
  key:
    type: string
    description: Unique configuration value key / ID.
  name:
    type: string
    description: Name of the configuration value.
  description:
    type: string
    description: Description for the configuration value.
  valueType:
    type: string
    description: Defines the type of value that must be specified for the configuration value.
  defaultValue:
    type: string
    description: Default value for the configuration value.
type: object
required:
  - key
  - name
  - description
  - valueType
  - defaultValue
title: ConfigurationValueDefinition
