get:
  description: This API returns a count of assets that have misconfigurations.
  operationId: get_misconfigurations_count_v1_misconfigurations_count_get
  parameters:
  - $ref: "../parameters/cloud_query.yaml"
  - $ref: "../parameters/ruleName_query.yaml"
  - $ref: "../parameters/includeAccounts_query.yaml"
  - $ref: "../parameters/excludeAccounts_query.yaml"
  - $ref: "../parameters/services_query.yaml"
  - $ref: "../parameters/region_query.yaml"
  - $ref: "../parameters/assetType_query.yaml"
  - $ref: "../parameters/assetId_query.yaml"
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: "../schemas/BaseResponse_CountModel_.yaml"
      description: Successful Response
    '400':
      content: {}
      description: Bad Request
    '404':
      description: Not Found
    '422':
      content:
        application/json:
          schema:
            $ref: "../schemas/HTTPValidationError.yaml"
      description: Validation Error
  summary: Get Misconfigurations Count
  tags:
  - Misconfiguration
parameters: []
