get:
  description: This API returns the list of assets that have misconfigurations.
  operationId: get_misconfigurations_v1_misconfigurations_get
  parameters:
  - $ref: "../parameters/cloud_query.yaml"
  - $ref: "../parameters/accountId_query.yaml"
  - $ref: "../parameters/notAccountId_query.yaml"
  - $ref: "../parameters/accountName_query.yaml"
  - $ref: "../parameters/notAccountName_query.yaml"
  - $ref: "../parameters/region_query.yaml"
  - $ref: "../parameters/notRegion_query.yaml"
  - $ref: "../parameters/date_query.yaml"
  - $ref: "../parameters/service_query.yaml"
  - $ref: "../parameters/notService_query.yaml"
  - $ref: "../parameters/assetType_query.yaml"
  - $ref: "../parameters/notAssetType_query.yaml"
  - $ref: "../parameters/ruleName_query.yaml"
  - $ref: "../parameters/assetId_query.yaml"
  - $ref: "../parameters/paginationKey_query.yaml"
  - $ref: "../parameters/paginationSize_query.yaml"
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: "../schemas/SpotResponse_PaginatedResponse_MisconfigurationModel__.yaml"
      description: Successful Response
    '400':
      content: {}
      description: Bad Request
    '404':
      description: Not Found
    '422':
      content:
        application/json:
          schema:
            $ref: "../schemas/HTTPValidationError.yaml"
      description: Validation Error
  summary: Get Misconfigurations
  tags:
  - Misconfiguration
parameters: []
