get:
  summary: "Elastigroup Azure Deployment - Deployment List"
  description: >
    Historical list of all deployments for an Azure Elastigroup
  operationId: "elastigroupAzureDeploymentList"
  tags:
    - Elastigroup Azure Scale Set VMs Deployment
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../commons/parameters/groupId.yaml"
  responses:
    200:
      $ref: "../responses/deployment.yaml"
    400:
      description: "Bad Request"

put:
  summary: "Elastigroup Azure Deployment - Start Deployment"
  description: >
    Start a new Azure Elastigroup deployment
  operationId: "elastigroupAzureDeploymentStart"
  tags:
    - Elastigroup Azure Scale Set VMs Deployment
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - $ref: "../../../commons/parameters/groupId.yaml"
  responses:
    200:
      $ref: "../responses/deployment.yaml"
    400:
      description: "Bad Request"
