type: object
title: Ocean Rightsizing Rule Recommendation Application Boundaries
description: >
  Determines the Ocean Rightsizing rule recommendation application boundaries.
properties:
  cpu:
    type: object
    properties:
      lower:
        type: integer
        description: the lower cpu in vCpu
        example: 0
      upper:
        type: integer
        description: the upper cpu in vCpu
        example: 100
  memory:
    type: object
    properties:
      lower:
        type: integer
        description: the lower memory in Gib
        minimum: 0
        example: 1
      upper:
        type: integer
        description: the upper memory in Gib
        minimum: 0
        example: 80