type: object
title: Ocean Rightsizing Rule Recommendation Application Intervals
description: >
  Determines the Ocean Rightsizing rule recommendation application intervals
properties:
  repetitionBasis:
    type: string
    description: The repetiotion basis
    enum: [ WEEKLY, MONTHLY ]
  monthlyRepetitionBasis:
    $ref: "../schemas/oceanRightsizingRuleMonthlyRepetitionBasis.yaml"
  weeklyRepetitionBasis:
    $ref: "../schemas/oceanRightsizingRuleWeeklyRepetitionBasis.yaml"