type: object
title: Ocean Rightsizing Rule Recommendation Application For HPA
description: >
  Determines by the rule if recommendation application is allowed for workloads with HPA definition.
properties:
  allowHPARecommendations:
    type: boolean
    default: false
    example: true
