type: object
title: Recommendation Application History
description: >
  A page of recommendation application history records.
properties:
  page:
    type: array
    items:
      $ref: "../schemas/oceanRightsizingRecommendationApplicationItem.yaml"

