type: object
title: Ocean Rightsizing Rule Recommendation Application Min Threshold
description: >
  Determines the Ocean Rightsizing rule recommendation application min threshold
properties:
  cpuPercentage:
    type: number
    example: 0.412
  memoryPercentage:
    type: number
    example: 1.36
