type: object
title: Ocean Rightsizing Rule Recommendation Application Overhead Values
description: >
  Determines the Ocean Rightsizing rule recommendation application overhead values
properties:
  cpuPercentage:
    type: number
    minimum: 0
    example: 0.8
    memoryPercentage:
      type: number
      minimum: 0
      example: 0.5
