type: object
title: Ocean Rightsizing Rule Recommendation Application Interval
description: >
  Determines the Ocean Rightsizing rule recommendation application interval
properties:
  repetitionBasis:
    type: string
    description: The repetition basis
    enum: [ WEEKLY, MONTHLY ]
  monthlyRepetitionBasis:
    $ref: "../schemas/oceanRightsizingRuleMonthlyRepetitionBasis.yaml"
  weeklyRepetitionBasis:
    $ref: "../schemas/oceanRightsizingRuleWeeklyRepetitionBasis.yaml"