type: object
title: Ocean Rightsizing Rule Recommendation Application Boundaries
description: >
  Determines the Ocean Rightsizing rule recommendation application boundaries
properties:
  cpu:
    type: object
    properties:
      lower:
        type: integer
        example: 0
      upper:
        type: integer
        example: 100
  memory:
    type: object
    properties:
      lower:
        type: integer
        minimum: 0
        example: 1
      upper:
        type: integer
        minimum: 0
        example: 80

        #todo shir - jira says it's this fields must not be negative. if true, add "minimum: 0"