type: object
title: Ocean Rightsizing Rule Recommendation Application Min Threshold
description: >
  Determines the extent of difference between current request and recommendation to trigger a change in percentage
properties:
  cpuPercentage:
    type: number
    minimum: 0.05
    maximum: 1
    default: 0.05
    example: 0.412
  memoryPercentage:
    type: number
    minimum: 0.05
    maximum: 1
    default: 0.05
    example: 0.36