type: object
title: Ocean Rightsizing Rule Recommendation Application Min Threshold
description: >
  Determines the Ocean Rightsizing rule recommendation application min threshold
properties:
  cpuPercentage:
    type: number
    minimum: 0
    example: 0.412
  memoryPercentage:
    type: number
    minimum: 0
    example: 1.36
  #todo shir - jira says it's this threshold is between 0-1. if true, add minimum and maximum and fix example or jira