type: object
title: Ocean Rightsizing Rule Recommendation Application Boundaries
description: >
  Determines the Ocean Rightsizing rule recommendation application boundaries
properties:
  cpu:
    type: object
    properties:
      lower:
        type: integer
        example: 0
      upper:
        type: integer
        example: 100
  memory:
    type: object
    properties:
      lower:
        type: integer
        example: 1
      upper:
        type: integer
        example: 80