type: object
title: Ocean Rightsizing Rule Recommendation Application For HPA
description: HPA Rightsizing Rule Recommendation Configuration
properties:
  allowHPARecommendations:
    type: boolean
    description: Determines by the rule if recommendation application is allowed for workloads with HPA definition.
    example: true
