type: object
title: Ocean Rightsizing Rule Recommendation Application Boundaries
description: >
  Determines the Ocean Rightsizing rule recommendation application boundaries.
properties:
  cpu:
    type: object
    properties:
      min:
        type: integer
        description: the minimal value of cpu in vCpu
        example: 0
      max:
        type: integer
        description: the maximal value of cpu in vCpu
        example: 100
  memory:
    type: object
    properties:
      min:
        type: integer
        description: the minimal value of memory in Gib
        minimum: 0
        example: 1
      max:
        type: integer
        description: the maximal value of memory in Gib
        minimum: 0
        example: 80