type: object
title: Ocean Rightsizing Rule Recommendation Application For HPA
description: >
  Determines by the rule if recommendation application is allowed for workloads with HPA definition. 
# todo shir should this description should be relevant for allowHPARecommendations parameter and not for the whole object? other parameters could be added to this object in the future
properties:
  allowHPARecommendations:
    type: boolean
    example: true
