type: object
title: "backendServiceConfig Object"
properties:
  backendServices:
    type: array
    items:
      type: object
      required:
        - backendServiceName
      properties:
        backendServiceName:
          type: string
          example: "bserv-2"
        locationType:
          type: string
          example: "global"
        scheme:
          type: string
          example: null
        namedPorts:
          type: object
          required:
            - name
            - ports
          properties:
            name:
              type: string
              example: "https"
            ports:
              type: array
              items:
                type: integer
                example: [443, 8443]
