type: object
title: "backendServiceConfig Object"
properties:
  backendServices:
    type: array
    items:
      type: object
      required:
        - backendServiceName
      properties:
        backendServiceName:
          type: string
          example: "bserv-2"
        locationType:
          type: string
          example: "global"
        scheme:
          type: string
          example: null
        namedPorts:
          type: object
          required:
            - name
            - ports
          properties:
            name:
              type: string
              example: "https"
            ports:
              type: array
              items:
                type: integer
                example: [443, 8443]
        backendBalancing:
          type: object
          title: Backend Balancing
          description: Configure how traffic is distributed across instance groups.
          properties:
            backendBalancingMode:
                type: string
                title: Backend Balancing Mode
                enum: [ "UTILIZATION", "RATE" ]
                example: UTILIZATION
            maxRatePerInstance:
              type: number
              title: Max Rate Per Instance
              description: If the backendBalancingMode is set to RATE, this field is required.
