type: object
title: "Shielded Instance Config"
description: You can use secure boot when you launch VMs using Elastigroup. This helps you comply with your security policies. In the instance configuration, use ‘secureBootEnabled’ set to True to enforce UEFI with secure boot. Elastigroup provisions VMs with secure boot, as long as the images supports UEFI.
properties:
  enableSecureBoot:
    type: boolean
    default: false
  enableIntegrityMonitoring:
    type: boolean
    default: false