type: object
title: "Shielded Instance Config"
description: To ensure compliance with security policies, you can enable Secure Boot when launching VMs via Elastigroup. Use the secureBootEnabled parameter within the instance configuration to enforce UEFI with Secure Boot. When set to true, Elastigroup will provision VMs with Secure Boot enabled, provided the selected image supports UEFI.
properties:
  enableSecureBoot:
    type: Boolean
    default: false
  enableIntegrityMonitoring:
    type: Boolean
    default: false