description: Successful response
content:
  application/json:
    schema:
      allOf:
        - $ref: ../../../../commons/schemas/paginatedResponseItemWrapper.yaml
        - type: object
          properties:
            request:
              type: object
              properties:
                url:
                  example: /cbi/v1/inventory/snapshot/{snapshotId}/service/{serviceId}/resource
                method:
                  example: GET
            response:
              type: object
              properties:
                items:
                  type: array
                  items:
                    $ref: ../schemas/resourceResponse.yaml
                kind:
                  example: spotinst:cbi:inventory:cloudServiceResourceItem
