get:
  summary: "Import Group From Application Gateway"
  description: >
    Given an application gateway, constructs a valid group configuration and returns it.
  operationId: "elastigroupAzureSpotVmsImportFromApplicationGateway"
  tags:
    - Elastigroup Azure Spot VMs
  parameters:
    - $ref: "../../../../../commons/parameters/accountId.yaml"
    - in: path
      name: resourceGroupName
      example: ExampleResourceGroup
      schema:
        type: string
    - in: path
      name: applicationGatewayName
      example: MyExampleApplicationGatewayImport
      schema:
        type: string
    - in: path
      name: backendPoolName
      example: MyExampleBackendPoolName
      schema:
        type: string
  responses:
    200:
      $ref: "../responses/importFromApplicationGateway.yaml"
    400:
      description: "Bad Request"
