type: object
properties:
  id:
    type: string
    description: "Provider account's ID.\r\nThis is the unique as defined by the service provider (e.g. AWS, Azure)."
    nullable: true
    example: aws~11111111111111
  name:
    type: string
    description: Provider account's Name.
    nullable: true
    example: Test
additionalProperties: false
description: Represents a (cloud) provider account ID.
