type: object
properties:
  id:
    type: string
    description: Policy's unique ID.
    nullable: true
    example: BE-ViewAllOnly
  name:
    type: string
    description: Policy's name.
    nullable: true
    example: Billing Engine View All Only
additionalProperties: false
description: Represents a FinOps authorization policy.
