type: object
properties:
  id:
    type: string
    description: Provider account ID. This is the unique ID from the service provider, such as AWS, Azure.
    nullable: true
    example: aws~11111111111111
  name:
    type: string
    description: Provider account's Name.
    nullable: true
    example: Test
additionalProperties: false
description: A cloud provider account ID.
