type: object
properties:
  id:
    type: string
    description: Cost type's unique ID.
    nullable: true
    example: Effective
  name:
    type: string
    description: Cost type's name.
    nullable: true
    example: Effective Cost
additionalProperties: false
description: Represents a FinOps cost type.
