type: object
properties:
  resetCostTypes:
    type: boolean
    description: If true, the existing list of cost types is emptied prior to performing the changes requested.
  costTypeChanges:
    type: array
    items:
      $ref: costTypeRequestListModification.yaml
    description: "List of cost types to add/remove.\r\nCost type applies to all accounts assigned to the user (regardless of how the user has access to the account).\r\nIf the user already has an existing list of cost types, the requested actions are applied to this existing\r\nlist unless resetCostTypes is true (which will clear all existing cost types first)."
    nullable: true
  organizationId:
    type: string
    description: "ID of the target Spot organization where the authorization configuration should be applied.\r\nOptional: Defaults to the caller's current Spot organization.\r\nIf specified, the ID must be one of these:\r\n- The caller's current Spot organization\r\n- A child Spot organization of the caller's current Spot organization"
    nullable: true
  resetAccounts:
    type: boolean
    description: "If true, the existing list of accounts is emptied prior to performing the \r\nchanges requested."
  accountChanges:
    type: array
    items:
      $ref: basicRequestListModification.yaml
    description: "List of accounts to add/remove.\r\nIf user or group already has an existing list of accounts, the requested actions will be applied to this existing \r\nlist unless resetAccounts is true (which will clear all existing accounts first)."
    nullable: true
  resetPolicies:
    type: boolean
    description: If true, the existing list of policies is emptied prior to performing the changes requested.
  policyChanges:
    type: array
    items:
      $ref: basicRequestListModification.yaml
    description: "List of policies to add/remove.\r\nIf user or group already has an existing list of policies, the requested actions will be applied to this existing \r\nlist unless resetPolicies is true (which will clear all existing policies first)."
    nullable: true
additionalProperties: false
description: The FinOps authorization changes for a user.
