type: object
properties:
  userId:
    type: string
    description: User's unique ID.
    nullable: true
    example: u-12345678
  beforeChanges:
    $ref: userAuthConfigResponseModel.yaml
  afterChanges:
    $ref: userAuthConfigResponseModel.yaml
additionalProperties: false
description: Represents the FinOps authorization configuration for a specific user (before and after changes). [kind/spotinst:cbi:authorization:user]
