type: object
properties:
  organizationId:
    type: string
    description: User's Spot organization ID.
    nullable: true
    example: '11111111111111'
  userId:
    type: string
    description: User's unique ID.
    nullable: true
    example: u-12345678
  costTypes:
    type: array
    items:
      $ref: authConfigCostType.yaml
    description: Cost types assigned to this user.
    nullable: true
  accounts:
    type: array
    items:
      $ref: authConfigAccount.yaml
    description: Provider account IDs assigned to this user.
    nullable: true
    example:
      - id: aws~11111111111111
        name: Test
  policies:
    type: array
    items:
      $ref: authConfigPolicy.yaml
    description: Auth policies assigned to this user.
    nullable: true
    example:
      - id: BE-ViewAllOnly
        name: Billing Engine View All Only
additionalProperties: false
description: The user's FinOps authorization configuration response model. [kind/spotinst:cbi:authorization:user]
