post:
  summary: "AWS Elastigroup - Deployment Actions"
  description:
    Apply a Detach action to a deployment
  operationId: "elastigroupAwsDeployment"
  tags:
    - "Elastigroup AWS"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "query"
      name: "rollId"
      example: "sbgd-9876"
      description: >
        The deployment id you want to stop
      schema:
        type: "string"
      required: true
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        Your Spot accountId associated with your token
      schema:
        type: "string"
      required: false
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/deployment-actions.yaml"
  responses:
    200:
      $ref: "../responses/deployment-actions.yaml"
    400:
      description: "Bad Request"

