put:
  summary: "AWS Elastigroup - Stop Deployment"
  description:
    Stop an existing deployment
  operationId: "elastigroupAwsStopDeployment"
  tags:
    - "Elastigroup AWS"
  parameters:
    - $ref: "../../../../commons/parameters/groupId.yaml"
    - in: "path"
      name: "rollId"
      example: "sbgd-9876"
      description: >
        The deployment id you want to stop
      schema:
        type: "string"
      required: true
    - in: "query"
      name: "accountId"
      example: "act-123abc"
      description: >
        Your Spotinst accountId associated with your token
      schema:
        type: "string"
      required: false
  requestBody:
    required: true
    content:
      application/json:
        schema:
          allOf:
            - $ref: "../schemas/stop-deployment.yaml"
  responses:
    200:
      $ref: "../responses/group-deployment-stop.yaml"
    400:
      description: "Bad Request"

