type: object
title: "Group Deploy Object"
required:
  - batchSizePercentage
  - gracePeriod
properties:
  batchSizePercentage:
    type: integer
    example: 20
    description: >
      (in percentage) the batch size of the deployment, i.e.: how many instances to replace in each batch
  gracePeriod:
    type: integer
    example: 300
    description: >
      (in seconds) the time until an instance becomes healthy in the load balancer