properties: {}
type: object
title: BERegisteredSetupAccountAzureConfig
description: Configuration settings used to collect Azure billing data. The target Spot account must be linked to an Azure billing account.
