properties:
  billingSource:
    $ref: BERegisteredSetupAccountAwsConfigBillingSource.yaml
    description: Configuration settings used to collect AWS billing data.
type: object
required:
  - billingSource
title: BERegisteredSetupAccountAwsConfig
description: Configuration settings used to collect AWS billing data. Requires that the target Spot account is linked to an AWS account with billing data (e.g. master payer account).
