properties:
  tableId:
    type: string
    description: ID of the BigQuery table which contains the billing data.
  datasetId:
    type: string
    description: ID of the BigQuery dataset to which the billing data is exported.
  projectId:
    type: string
    description: ID of the Google project to which the billing data is exported.
type: object
required:
  - tableId
  - datasetId
  - projectId
title: BERegisteredSetupAccountGcpBillingConfig
