properties:
  googleBillingConfiguration:
    $ref: BERegisteredSetupAccountGcpBillingConfig.yaml
    description: Configuration settings used to collect Google billing data.
type: object
required:
  - googleBillingConfiguration
title: BERegisteredSetupAccountGcpConfig
description: Configuration settings used to collect Google billing data. The target Spot account must be linked to a Google project where the billing data is exported.
