properties:
  tableId:
    type: string
    description: The BigQuery table ID that is used to export the billing data.
  datasetId:
    type: string
    description: The BigQuery dataset ID that is used to export the billing data.
  projectId:
    type: string
    description: The Google project ID that is used to export the billing data.
type: object
required:
  - tableId
  - datasetId
  - projectId
title: BERegisteredSetupAccountGcpBillingConfig
