properties:
  bucket:
    type: string
    description: The name of the AWS S3 bucket where the AWS CUR is stored.
  region:
    type: string
    description: The AWS buckets AWS region (e.g. us-east-1).
  pathPrefix:
    type: string
    description: The prefix path and report name generated for the AWS CUR you configured.
type: object
required:
  - bucket
  - region
  - pathPrefix
title: BERegisteredSetupAccountAwsConfigBillingSource
