properties: {}
type: object
title: BERegisteredSetupAccountAzureConfig
description: Configuration settings used to collect Azure billing data. Requires that the target Spot account is linked to an Azure billing account.
