get:
  description: 'It''s acceptable to have zero defaults, but more than one should

    be cleaned up. This can be done by updating an existing entry to set is_default=True.'
  operationId: get_target_account_get_default
  parameters:
  - $ref: "../parameters/workspace_id.yaml"
  responses:
    '200':
      content: {}
      description: Success
    '400':
      content: {}
      description: Bad Request
  summary: Only return the default entry
  tags:
  - Connect Targets
parameters: []
