description: A list of Spark applications (can be a single app)
content:
  application/json:
    schema:
      allOf:
        - $ref: "../../../../commons/schemas/responseItemWrapper.yaml"
        - type: object
          properties:
            response:
              type: object
              description: >
                response body
              properties:
                items:
                  type: array
                  items:
                    $ref: "../schemas/oceanSparkApplication.yaml"
