type: object
title: Logging configuration
properties:
  export:
    type: object
    title: Logging Export Configuration.
    properties:
      s3:
        type: object
        title: Logging S3 Export configuration.
        description: |
          Exports your cluster's logs to the S3 bucket and subdir configured on the S3 [data integration](/#operation/DataIntegrationCreate) given.
          Each file contains logs of 3 minutes where each log is separated by a new line and saved as a JSON.
          The file formats are `subdir`/`accountId`_`oceanId`_`oceanName`_`startTime`.log
          If no subdir was configured, the files will be saved in the root of the bucket.
        required:
          - id
        properties:
          id:
            type: string
            description: The identifier of The S3 data integration to export the logs to.
            example: di-123
