openapi: "3.0.0"
info:
  version: "1.0"
  description: |
    Welcome to the Spot by NetApp OpenAPI Specification.
    Here you will find REST definitions for all Spot products and platform administration tasks.

    The API is hosted at `https://api.spotinst.io` and requires Bearer Token
    Authentication.

    For more information on how to use the Spot platform, including user guides,
    developer guides, concepts, and tutorials, see the external [Spot Documentation](https://docs.spot.io/).
  title: Spot by NetApp API
  x-logo:
    url: https://docs.spot.io/_media/images/spot.png
    altText: SpotByNetAppLogo
    href: https://docs.spot.io/api
  contact:
    email: support@spot.io
externalDocs:
  url: https://docs.spot.io/
servers:
  - url: https://api.spotinst.io
security:
  - auth: [ ]

components:
  securitySchemes:
    auth:
      $ref: ../commons/security.yaml#/components/securitySchemes/BearerAuth

tags:
  - name: Managed Instance AWS
    description: |
      Managed Instance is a Spot solution for launching and managing a single compute instance.
      On the AWS cloud, for a standard single instance workload, an On-Demand EC2 instance is launched.
      The instance is expected to be highly available, easily manageable, and integrate well with additional services and monitoring tools.
      For more information please review the concepts section.
    externalDocs:
      description: Managed Instance for AWS Concepts and Tutorials
      url: https://docs.spot.io/managed-instance/

x-tagGroups:
  - name: Managed Instance
    tags:
      - Managed Instance AWS

paths:
  /aws/ec2/managedInstance:
    $ref: ../services/managedInstance/aws/paths/managed.yaml
  /aws/ec2/managedInstance/{MI_ID}:
    $ref: ../services/managedInstance/aws/paths/managedID.yaml
  /aws/ec2/managedInstance/{MI_ID}/pause:
    $ref: ../services/managedInstance/aws/paths/managedIDPause.yaml
  /aws/ec2/managedInstance/{MI_ID}/resume:
    $ref: ../services/managedInstance/aws/paths/managedIDResume.yaml
  /aws/ec2/managedInstance/{MI_ID}/recycle:
    $ref: ../services/managedInstance/aws/paths/managedIDRecycle.yaml
  /aws/ec2/managedInstance/{MI_ID}/costs:
    $ref: ../services/managedInstance/aws/paths/managedIDCosts.yaml
  /aws/ec2/managedInstance/{MI_ID}/status:
    $ref: ../services/managedInstance/aws/paths/managedIDStatus.yaml
  /aws/ec2/managedInstance/{MI_ID}/volume/{volumeId}:
    $ref: ../services/managedInstance/aws/paths/managedIDDeleteVolume.yaml
  /aws/ec2/managedInstance/migration:
    $ref: ../services/managedInstance/aws/paths/migration-mi.yaml
  /aws/ec2/managedInstance/migration/{MIGRATION_ID}:
    $ref: ../services/managedInstance/aws/paths/migrationStatus-mi.yaml
  /aws/ec2/managedInstance/state:
    $ref: ../services/managedInstance/aws/paths/state/updateManagedInstanceStates.yaml

