openapi: "3.0.0"
info:
  version: "1.0"
  description: |
    Welcome to the Spot by NetApp OpenAPI Specification.
    Here you will find REST definitions for all Spot products and platform administration tasks.

    The API is hosted at `https://api.spotinst.io` and requires Bearer Token
    Authentication.

    For more information on how to use the Spot platform, including user guides,
    developer guides, concepts, and tutorials, see the external [Spot Documentation](https://docs.spot.io/).
  title: Spot by NetApp API
  x-logo:
    url: https://docs.spot.io/_media/images/spot.png
    altText: SpotByNetAppLogo
    href: https://docs.spot.io/api
  contact:
    email: support@spot.io
externalDocs:
  url: https://docs.spot.io/
servers:
  - url: https://api.spotinst.io
security:
  - auth: [ ]

components:
  securitySchemes:
    auth:
      $ref: ../commons/security.yaml#/components/securitySchemes/BearerAuth

tags:
  - name: Audit Service
    externalDocs:
      url: https://docs.spot.io/api/#tag/Audit-Service

  - name: Health Check Service
    externalDocs:
      url: https://docs.spot.io/elastigroup/tools-integrations/custom-health-check-service

  - name: Notifications Service
    description: |
      A Spot Notifications service enables you a fast, flexible, fully managed push notification service that lets you know about major events that happened in your Spot account.Ö¿ Spot Notifications makes it simple and cost-effective to get push notifications to your email address, HTTP, HTTPS or AWS SNS (Simple Notifications Service).

  - name: Insights Service

x-tagGroups:
    tags:
      - Audit Service
      - Health Check Service
      - Notifications Service
      - Insights Service

paths:
  /audit/events:
    $ref: ../services/administration/general/paths/auditListAll.yaml
  /healthCheck:
    $ref: ../services/administration/general/paths/healthCheck.yaml
  /healthCheck/{HEALTHCHECK_ID}:
    $ref: ../services/administration/general/paths/healthCheckID.yaml
  /events/notification/accountPolicy:
    $ref: ../services/administration/general/paths/accountPolicy.yaml
  /events/subscription:
    $ref: ../services/administration/general/paths/subscription.yaml
  /events/subscription/{subscriptionId}:
    $ref: ../services/administration/general/paths/subscriptionID.yaml
  /insights/instanceCosts/export:
    $ref: ../services/administration/general/paths/organizationInstancesCosts.yaml
  /insights/dataIntegration:
    $ref: ../services/dataIntegration/paths/dataIntegrations.yaml
  /insights/dataIntegration/{dataIntegrationId}:
    $ref: ../services/dataIntegration/paths/dataIntegration.yaml
  /insights/savings:
    $ref: ../services/insights/paths/organizationSavings.yaml

