parameters: []
post:
  description: "for specific service in specific organization\nExpected payload:-\n{\n
    \   \"alias\": \"<alias_name>\"\n}"
  operationId: post_setting_check_alias
  parameters:
  - $ref: "../parameters/service.yaml"
  responses:
    '200':
      content: {}
      description: Success
    '400':
      content: {}
      description: Bad Request
  summary: Checks whether given Alias name is available for use
  tags:
  - Connect Settings
