parameters: []
post:
  description: 'Checks whether given Alias name is available for use

    for the selected service in the current organization.'
  operationId: post_setting_check_alias
  parameters:
  - $ref: "../parameters/service.yaml"
  requestBody:
    content:
      application/json:
        schema:
          $ref: "../../schemas/AliasAvailableRequest.yaml"
    required: true
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: "../../schemas/Base_AliasAvailableResponse.yaml"
      description: Success
    '400':
      content: {}
      description: Bad Request
  summary: Get Alias Name Availability
  tags:
  - Connect Settings
  x-codegen-request-body-name: payload
