openapi: "3.0.0"
info:
  description: "Spot Elastigroup - GCP"
  version: "1.0.0"
  title: "Spot Elastigroup - GCP"
  contact:
    email: "support@spot.io"
servers:
- url: https://api.spotinst.io/gcp/gce
schemes:
- "https"
security:
  - BearerAuth: []
tags:
- name: "Elastigroup GCP"
  description: "Elastigroup for GCP"
paths:
  /group:
    $ref: './paths/groups.yaml'
  /group/{groupId}:
    $ref: './paths/group.yaml'
  /gcp/gce/group/gke/import:
    $ref: 'paths/gke-import.yaml'
  /group/{groupId}/status:
    $ref: 'paths/group-status.yaml'
  /group/{groupId}/events:
    $ref: 'paths/group-event.yaml'
  /group/{groupId}/log:
    $ref: 'paths/group-elastilog.yaml'
  /group/{groupId}/costs:
    $ref: 'paths/group-costs.yaml'
  /group/{groupId}/scale/up:
      $ref: 'paths/group-scale-up.yaml'
  /group/{groupId}/scale/down:
    $ref: 'paths/group-scale-down.yaml'
  /gcp/gce/group/{groupId}/roll:
    $ref: 'paths/group-rolls.yaml'
  /gcp/gce/group/{groupId}/roll/{rollId}:
    $ref: 'paths/group-roll.yaml'
  /group/{groupId}/detachInstances:
    $ref: 'paths/group-detach-instances.yaml'
  /instance/{instanceId}:
    $ref: 'paths/instance-status.yaml'
  /instance/{instanceId}/lock:
    $ref: 'paths/instance-lock.yaml'
  /instance/{instanceId}/unlock:
    $ref: 'paths/instance-unlock.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../../commons/security.yaml#/components/securitySchemes/BearerAuth'
