openapi: "3.0.0"
info:
  description: "Spotinst Elastigroup - GCP"
  version: "1.0.0"
  title: "Spotinst Elastigroup - GCP"
  contact:
    email: "support@spotinst.com"
servers:
- url: https://api.spotinst.io/gcp/gce
schemes:
- "https"
security:
  - BearerAuth: []
tags:
- name: "Elastigroup GCP"
  description: "Elastigroup for GCP"
paths:
  /group:
    $ref: './paths/groups.yaml'
  /group/{groupId}:
    $ref: './paths/group.yaml'
  /group/{groupId}/status:
    $ref: 'paths/group-status.yaml'
  /group/{groupId}/events:
    $ref: 'paths/group-event.yaml'
  /group/{groupId}/log:
    $ref: 'paths/group-elastilog.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../../commons/security.yaml#/components/securitySchemes/BearerAuth'
