get:
  tags:
    - Inventory Resources
  summary: Get resource summary
  description: Returns resource summary for the provided Service ID.
  operationId: getResourceSummaryCbiV1InventorySnapshotSnapshotIdServiceServiceIdResourceSummaryGet
  parameters:
    - name: snapshotId
      in: path
      required: true
      schema:
        type: string
        format: date-time
        description: Snapshot ID
      description: Snapshot ID
    - name: serviceId
      in: path
      required: true
      schema:
        type: string
        description: Service ID
      description: Service ID
    - name: accountId
      in: query
      required: false
      schema:
        anyOf:
          - type: string
          - type: 'null'
        description: Spot account ID
      description: Spot account ID
    - name: subAccountId
      in: query
      required: false
      schema:
        anyOf:
          - type: string
          - type: 'null'
        description: Subaccount ID
      description: Subaccount ID
    - name: resourceId
      in: query
      required: false
      schema:
        type: string
        description: Resource ID.
      description: Resource ID.
  responses:
    '200':
      $ref: ../responses/get200cbiV1InventorySnapshotIdServiceIdResourceSummary.yaml
    '400':
      content:
        application/json:
          schema:
            $ref: ../../../../commons/schemas/errorResponse.yaml
      description: Invalid request error response. Adjust the request before retrying.
    '404':
      content:
        application/json:
          schema:
            $ref: ../../../../commons/schemas/errorResponse.yaml
      description: Not found error response. The requested resource does not exist.
    '422':
      description: Error response.
      content:
        application/json:
          schema:
            $ref: ../../../../commons/schemas/errorResponse.yaml
