openapi: "3.0.0"
info:
  description: "Spotinst Elastigroup - AWS"
  version: "1.0.0"
  title: "Spotinst Elastigroup - AWS"
  contact:
    email: "support@spotinst.com"
servers:
- url: https://api.spotinst.io/compute/aws
components:
  securitySchemes:
    BearerAuth:
      $ref: '../../../commons/security.yaml#/components/securitySchemes/BearerAuth'
schemes:
- "https"
tags:
- name: "Elastigroup AWS"
  description: "Elastigroup for Amazon Web Services"
paths:
  /group:
    $ref: 'paths/groups.yaml'
  /group/{id}:
