components:
  parameters:
    accountId:
      in: "query"
      name: "accountId"
      example: "act-123456789"
      description: >
        Spot Account ID
      schema:
        type: "string"
      required: true
