properties:
  args:
    anyOf:
    - items:
        type: string
      type: array
    - type: 'null'
    description: 'Certain misconfiguration rules have arguments. This field contains
      the arguments in         the form of an comma separated array. Example: ["MongoDB",
      "TCP", "27017"]'
    title: Args
  ruleDescription:
    description: Describes the rule.
    title: Ruledescription
    type: string
  ruleName:
    description: An unique name of the rule.
    title: Rulename
    type: string
  ruleTitle:
    description: A user friendly representation of the rule name
    title: Ruletitle
    type: string
  severity:
    description: The severity of the rule.
    examples:
    - High
    title: Severity
    type: string
  state:
    description: The state of the misconfiguration. It is either open or closed.
    examples:
    - open
    title: State
    type: string
required:
- ruleName
- ruleTitle
- ruleDescription
- args
- severity
- state
title: MisconfigurationWhatModel
type: object
