properties:
  organizationId:
    description: The Spot Organization ID.
    title: Organizationid
    type: string
  what:
    $ref: ./MisconfigurationWhatModel.yaml
  when:
    $ref: ./MisconfigurationWhenModel.yaml
  where:
    $ref: ./MisconfigurationWhereModel.yaml
  who:
    $ref: ./MisconfigurationWhoModel.yaml
required:
- organizationId
- when
- what
- where
- who
title: MisconfigurationModel
type: object
