properties:
  accountId:
    description: The cloud account ID. For AWS this is the account ID. For Azure,
      this is the subscription ID.
    title: Accountid
    type: string
  assetId:
    anyOf:
    - type: string
    - type: 'null'
    description: The asset's ID (a cloud resource).
    title: Assetid
  assetName:
    anyOf:
    - type: string
    - type: 'null'
    description: The name of the asset ID.
    title: Assetname
  assetType:
    anyOf:
    - type: string
    - type: 'null'
    description: The type of cloud resource for the service.
    title: Assettype
  findingLocation:
    description: 'For a misconfiguration: the cloud resource or a subelement of the
      cloud resource.                        For a vulnerability: the cloud resource,
      an OS image, or a filename.'
    title: Findinglocation
    type: string
  region:
    description: The cloud region.
    title: Region
    type: string
  service:
    description: The cloud service.
    title: Service
    type: string
required:
- accountId
- service
- assetId
- assetName
- assetType
- region
- findingLocation
title: MisconfigurationWhereModel
type: object
