properties:
  organizationId:
    description: The Spot Organization Id.
    title: Organizationid
    type: string
  what:
    $ref: ./MisconfigurationWhatModel.yaml
  when:
    $ref: ./MisconfigurationWhenModel.yaml
  where:
    $ref: ./MisconfigurationWhereModel.yaml
required:
- organizationId
- when
- what
- where
title: MisconfigurationModel
type: object
