properties:
  lastSeen:
    description: The date the finding was most recently found (YYYY-MM-DD).
    title: Lastseen
    type: string
  suppressedAt:
    anyOf:
    - format: date-time
      type: string
    - type: 'null'
    description: When the finding was suppressed.
    title: Suppressedat
required:
- lastSeen
- suppressedAt
title: MisconfigurationWhenModel
type: object
