properties:
  accountId:
    description: The cloud account id. For AWS this is the account id. For Azure,
      this is the subscription id.
    title: Accountid
    type: string
  assetId:
    anyOf:
    - type: string
    - type: 'null'
    description: An id to identify the asset. It represents a cloud resource.
    title: Assetid
  assetName:
    anyOf:
    - type: string
    - type: 'null'
    description: A user friendly representation of the asset id.
    title: Assetname
  assetType:
    anyOf:
    - type: string
    - type: 'null'
    description: The type of cloud resource for the service.
    examples:
    - security_groups
    title: Assettype
  item:
    anyOf:
    - type: string
    - type: 'null'
    description: 'Identifies an entity of the asset. Example: An asset of type security_groups
      may have         more than one rule. Each such rule is an item.'
    title: Item
  itemName:
    anyOf:
    - type: string
    - type: 'null'
    description: A user friendly representation of the item.
    title: Itemname
  region:
    description: The cloud region.
    examples:
    - us-east-1
    title: Region
    type: string
  service:
    description: The cloud service.
    examples:
    - EC2
    title: Service
    type: string
required:
- accountId
- service
- assetId
- assetName
- assetType
- region
- item
- itemName
title: MisconfigurationWhereModel
type: object
