properties:
  suppressedBy:
    anyOf:
    - type: string
    - type: 'null'
    description: The user who suppressed the finding.
    title: Suppressedby
required:
- suppressedBy
title: MisconfigurationWhoModel
type: object
