properties:
  args:
    anyOf:
    - items:
        type: string
      type: array
    - type: 'null'
    description: 'Certain misconfiguration rules have arguments. This field contains
      the arguments in         the form of an comma separated array. Example: ["MongoDB",
      "TCP", "27017"]'
    title: Args
  isSuppressed:
    anyOf:
    - type: boolean
    - type: 'null'
    description: If this finding is suppressed, the value is True.
    title: Issuppressed
  ruleDescription:
    description: Description of the rule.
    title: Ruledescription
    type: string
  ruleName:
    description: The unique name of the rule.
    title: Rulename
    type: string
  ruleTitle:
    description: The name of the rule.
    title: Ruletitle
    type: string
  severity:
    description: The severity of the rule.
    title: Severity
    type: string
  state:
    description: The state of the misconfiguration. It is either open or closed.
    title: State
    type: string
required:
- ruleName
- ruleTitle
- ruleDescription
- args
- severity
- state
- isSuppressed
title: MisconfigurationWhatModel
type: object
