properties:
  accountId:
    description: A comma-separated list of cloud account IDs. For AWS this is the
      account ID. For Azure, this is the subscription ID.
    title: Accountid
    type: string
  assetId:
    description: The asset's ID (a cloud resource).
    title: Assetid
    type: string
  assetName:
    description: The name of the asset ID.
    title: Assetname
    type: string
  assetType:
    description: A comma-separated list of cloud resources for the service.
    title: Assettype
    type: string
  findingLocation:
    description: 'For a misconfiguration: the cloud resource or a subelement of the
      cloud resource.                        For a vulnerability: the cloud resource,
      an OS image, or a filename.'
    title: Findinglocation
    type: string
  region:
    description: A comma-separated list of cloud regions.
    title: Region
    type: string
  service:
    description: The cloud service.
    title: Service
    type: string
required:
- accountId
- service
- assetId
- assetName
- assetType
- region
- findingLocation
title: MisconfigurationWhereModel
type: object
