properties:
  lastSeen:
    description: The date the finding was most recently found (YYYY-MM-DD).
    title: Lastseen
    type: string
  suppressedAt:
    description: When the finding was suppressed.
    format: date-time
    title: Suppressedat
    type: string
required:
- lastSeen
- suppressedAt
title: MisconfigurationWhenModel
type: object
