properties:
  error:
    anyOf:
    - $ref: ./ErrorModel.yaml
    - type: 'null'
  request:
    $ref: ./RequestModel.yaml
  response:
    allOf:
    - $ref: ./PaginatedResponse_MisconfigurationModel_.yaml
  responseTime:
    title: Responsetime
    type: number
required:
- request
title: SpotResponse[PaginatedResponse[MisconfigurationModel]]
type: object
