type: object
title: Configurations object
required:
  - file
properties:
  file:
    type: object
    description: Configurations file for the group
    properties:
      bucket:
        type: string
        description: S3 bucket name of the configurations file for the instance group
        example: "spot-labs"
      key:
        type: string
        description: S3 key name of the configurations file for the instance group
        example: "emr_configurations.json"