type: object
title: Block Device Config Object
description: Amazon EBS volume specification attached to a cluster instance.
required:
  - volumeSpecification
  - volumesPerInstance
properties:
  volumeSpecification:
    $ref: "./volumeSpecification.yaml"
  volumesPerInstance:
    type: integer
    description: >
      Number of EBS volumes with a specific volume configuration that will be associated with
      every instance in the instance group - required if `ebsConfiguration` is defined.
    example: 1

