type: object
title: Json Configuration Object
description: >
  EMR cluster configuration in JSON format.
  You can use `jsonConfiguration` or `file`, but not both.
  Can be used in `masterGroup`, `coreGroup`, and `taskGroup`.
requierd:
  - jsonConfiguration
properties:
  jsonConfiguration:
    type: object
    properties:
      classification:
        type: string
        description: The grouping within a configuration.
        example: "mapred-site"
      properties:
        type: object
        description: >
          Within a configuration classification, a set of properties that represent the settings that
          you want to change in the configuration file.
          Duplicates not allowed.
        example: {"mapred.tasktracker.map.tasks.maximum": 2}
      configuartions:
        type: array
        description: >
         Array of objects with any keys.
         This can include additional levels (i.e., nested) of classification, properties, and configurations.
        items:
          $ref: "./nestedConfiguration.yaml"
