summary: Ocean Spark

get:
  summary: "List Applications"
  description: >
    List Spark applications on all Ocean Spark clusters in the specified account.
    This endpoint is paginated (cursor pagination).
  operationId: "OceanSparkApplicationList"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/query/oceanSparkClusterId.yaml"
    - $ref: "../parameters/query/oceanSparkJobId.yaml"
    - $ref: "../parameters/query/oceanSparkApplicationSubmissionSource.yaml"
    - $ref: "../parameters/query/oceanSparkApplicationType.yaml"
    - $ref: "../parameters/query/oceanSparkApplicationState.yaml"
    - $ref: "../parameters/query/userId.yaml"
    - $ref: "../parameters/query/searchTerm.yaml"
    - $ref: "../parameters/query/minCreatedAt.yaml"
    - $ref: "../parameters/query/maxCreatedAt.yaml"
    - $ref: "../parameters/query/minUpdatedAt.yaml"
    - $ref: "../parameters/query/maxUpdatedAt.yaml"
    - $ref: "../parameters/query/pageSize.yaml"
    - $ref: "../parameters/query/after.yaml"
    - $ref: "../parameters/query/before.yaml"
    - $ref: "../parameters/query/order.yaml"
    - $ref: "../parameters/query/orderBy.yaml"
  responses:
    200:
      $ref: "../responses/paginatedApplications.yaml"
    400:
      description: "Bad Request"
