summary: Ocean Spark

get:
  summary: "Download Driver log"
  description: >
    Download an archive of the driver logs for a finished spark application.
  operationId: "OceanSparkClusterApplicationLogsArchive"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/path/oceanSparkClusterId.yaml"
    - $ref: "../parameters/path/oceanSparkApplicationId.yaml"
  responses:
    200:
      $ref: "../responses/logsArchive.yaml"
    400:
      description: "Bad Request"
