summary: Ocean Spark

get:
  summary: "Stream Kubernetes events"
  description: >
    Stream Kubernetes events about the Spark application in real time.
  operationId: "OceanSparkClusterApplicationKubeEventsLive"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/path/oceanSparkClusterId.yaml"
    - $ref: "../parameters/path/oceanSparkApplicationId.yaml"
  responses:
    200:
      $ref: "../responses/kubeEventsLive.yaml"
    400:
      description: "Bad Request"
