summary: Ocean Spark

get:
  summary: "Download Executor logs"
  description: >
    Download an archive of the executor logs for a finished spark application.
  operationId: "OceanSparkClusterApplicationExecutorLogsArchive"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/path/oceanSparkClusterId.yaml"
    - $ref: "../parameters/path/oceanSparkApplicationId.yaml"
  responses:
    200:
      $ref: "../responses/executorLogsArchive.yaml"
    400:
      description: "Bad Request"
