summary: Ocean Spark

get:
  summary: "Get Application"
  description: >
    Describe a Spark application in an Ocean Spark cluster.
  operationId: "OceanSparkClusterApplicationGet"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/path/oceanSparkClusterId.yaml"
    - $ref: "../parameters/path/oceanSparkApplicationId.yaml"
  responses:
    200:
      $ref: "../responses/applications.yaml"
    400:
      description: "Bad Request"
