summary: Ocean Spark

get:
  summary: "Stream Driver log"
  description: >
    Stream the driver log of a Spark application in real time.
  operationId: "OceanSparkClusterApplicationLogsLive"
  tags:
    - "Ocean Spark"
  parameters:
    - $ref: "../../../../commons/parameters/nonRequiredAccountId.yaml"
    - $ref: "../parameters/path/oceanSparkClusterId.yaml"
    - $ref: "../parameters/path/oceanSparkApplicationId.yaml"
  responses:
    200:
      $ref: "../responses/logsLive.yaml"
    400:
      description: "Bad Request"
