type: object
title: Ocean AKS Linux OS Config
description: |
  Custom Linux OS configuration
properties:
  sysctls:
    type: object
    properties:
      vmMaxMapCount:
        type: integer
        description: |
          Maximum number of memory map areas a process may have.
          Can be configured only if OS type is Linux.
        example: 79550
        minimum: 65530
        maximum: 262144
