description: "The number of low misconfigurations found for the asset.\n        <br>\n
  \       Enter either a number or prefix it with one of these operators:\n        <table>\n
  \       <tr>\n        <th>Operator</th>\n        <th>Notation</th>\n        <th>Example</th>\n
  \       </tr>\n        <tr>\n        <td>Equals</td>\n        <td>No prefix or \\~eq\\~</td>\n
  \       <td>10 or \\~eq\\~10</td>\n        </tr>\n        <tr>\n        <td>Not
  equals</td>\n        <td>\\~neq\\~</td>\n        <td>\\~neq\\~10</td>\n        </tr>\n
  \       <tr>\n        <td>Greater than</td>\n        <td>\\~gt\\~</td>\n        <td>\\~gt\\~10</td>\n
  \       </tr>\n        <tr>\n        <td>Greater than equals</td>\n        <td>\\~gte\\~</td>\n
  \       <td>\\~gte\\~10</td>\n        </tr>\n        <tr>\n        <td>Less than</td>\n
  \       <td>\\~lt\\~</td>\n        <td>\\~lt\\~10</td>\n        </tr>\n        <tr>\n
  \       <td>Less than equals</td>\n        <td>\\~lte\\~</td>\n        <td>\\~lte\\~10</td>\n
  \       </tr>\n        <tr>\n        <td>Between two numbers</td>\n        <td>\\~bt\\~</td>\n
  \       <td>\\~bt\\~10,20</td>\n        </tr>\n        </table>\n        "
in: query
name: lowMisconfigCount
required: false
schema:
  description: "The number of low misconfigurations found for the asset.\n        <br>\n
    \       Enter either a number or prefix it with one of these operators:\n        <table>\n
    \       <tr>\n        <th>Operator</th>\n        <th>Notation</th>\n        <th>Example</th>\n
    \       </tr>\n        <tr>\n        <td>Equals</td>\n        <td>No prefix or
    \\~eq\\~</td>\n        <td>10 or \\~eq\\~10</td>\n        </tr>\n        <tr>\n
    \       <td>Not equals</td>\n        <td>\\~neq\\~</td>\n        <td>\\~neq\\~10</td>\n
    \       </tr>\n        <tr>\n        <td>Greater than</td>\n        <td>\\~gt\\~</td>\n
    \       <td>\\~gt\\~10</td>\n        </tr>\n        <tr>\n        <td>Greater
    than equals</td>\n        <td>\\~gte\\~</td>\n        <td>\\~gte\\~10</td>\n        </tr>\n
    \       <tr>\n        <td>Less than</td>\n        <td>\\~lt\\~</td>\n        <td>\\~lt\\~10</td>\n
    \       </tr>\n        <tr>\n        <td>Less than equals</td>\n        <td>\\~lte\\~</td>\n
    \       <td>\\~lte\\~10</td>\n        </tr>\n        <tr>\n        <td>Between
    two numbers</td>\n        <td>\\~bt\\~</td>\n        <td>\\~bt\\~10,20</td>\n
    \       </tr>\n        </table>\n        "
  title: Lowmisconfigcount
  type: string
