title: ConfigMapKeySelector
required:
  - key
type: object
properties:
  key:
    title: Key
    type: string
    description: The key to select.
  name:
    title: Name
    type: string
    description: >-
      Name of the referent. More info:
      https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
  optional:
    title: Optional
    type: boolean
    description: Specify whether the ConfigMap or its key must be defined
