title: Intelligent Traffic Flow (ITF) Configuration
type: object
description: |
  Contains the configuration details of Intelligent Traffic Flow (ITF).
properties:
  fixedTargetGroups:
    type: boolean
    description: >
      Boolean to control whether to keep the set of target groups fixed. When
      set to true, all target groups will be created in advance upon
      create/update group, and will not be deleted even when not being used
      anymore.
    default: false
    example: false
  weightStrategy:
    type: string
    description: >
      Distribution strategy (either 'vcpu' or 'custom'). 'Custom' strategy can
      be set only when the group is configured with custom weights.
    enum:
      - vcpu
      - custom
    default: vcpu
    example: custom
  migrationHealthinessThreshold:
    type: integer
    description: >
      Threshold for the minimum healthiness level of the target groups that is
      needed before activating the ITF rules. Integer representing the
      percentage of healthy instances within the target groups. Valid values:
      integer between 0-100.
    default: 50
    example: 80
  loadBalancers:
    type: array
    description: |
      The load balancer associated with the ITF. Array with a single element.
    items:
      $ref: ./itfLoadBalancerConfig.yaml
  targetGroupConfig:
    $ref: ./itfTargetGroupConfigUpdateGroup.yaml
