title: ITF Load Balancer Configuration
type: object
description: |
  Contains the configuration details of an ITF load balancer.
required:
  - loadBalancerArn
  - listenerRules
properties:
  loadBalancerArn:
    type: string
    description: |
      Identifier of the load balancer in AWS.
    example: >-
      arn:aws:elasticloadbalancing:us-west-2:123456789012:loadbalancer/app/my-load-balancer/50dc6c495c0c9188
  listenerRules:
    type: array
    description: >
      The listener rules that should be maintained by ITF. Array with a minimum
      of 1 element.
    items:
      $ref: ./itfListenerRuleMigrationConfig.yaml
  defaultStaticTargetGroups:
    type: array
    description: A default static target group on the rule. Array with a single element.
    items:
      $ref: ./itfStaticTargetGroupConfig.yaml
