type: object
properties:
  vpcId:
    type: string
    description: >
      The ID of the AWS VPC for the targets. Valid values: any string which is
      not empty or null.
    example: vpc-0410a20ec1702a537
  healthCheckPath:
    type: string
    description: |
      The destination for health checks on the targets.
    example: /index.html
  healthCheckProtocol:
    type: string
    description: |
      HTTP, HTTPS are already listed under the enum below, no need to repeat.
    enum:
      - HTTP
      - HTTPS
    default: HTTP
    example: HTTP
  healthCheckPort:
    type: string
    description: >
      The port to use to connect with the target. Valid values: 1-65535 or
      "traffic-port".
    default: '80'
    example: traffic-port
  healthCheckIntervalSeconds:
    type: integer
    description: >
      The approximate amount of time, in seconds, between health checks of an
      individual target. Valid values: integer between 5-300.
    default: 30
    example: 40
  healthCheckTimeoutSeconds:
    type: integer
    description: >
      The amount of time, in seconds, during which no response means a failed
      health check. Valid values: integer between 2-120.
    default: 5
    example: 20
  healthyThresholdCount:
    type: integer
    description: >
      The number of consecutive health checks successes required before
      considering an unhealthy target healthy. Valid values: integer between
      2-10.
    default: 5
    example: 3
  unhealthyThresholdCount:
    type: integer
    description: >
      The number of consecutive health check failures required before
      considering the target unhealthy. Valid values: integer between 2-10.
    default: 2
    example: 4
  port:
    type: integer
    description: >
      The port on which the targets are listening. Not used if the target is a
      Lambda function. Valid values: integer between 1-65535.
    example: 80
  protocol:
    type: string
    description: |
      The protocol to use for routing traffic to the targets.
    enum:
      - HTTP
      - HTTPS
    example: HTTP
  protocolVersion:
    type: string
    description: |
      The protocol version.
    default: HTTP1
    enum:
      - GRPC
      - HTTP1
      - HTTP2
    example: HTTP1
  tags:
    type: array
    description: |
      The tags to assigned with the created target groups
    default: []
    example:
      - creator: John Doe
    items:
      type: object
      properties:
        tagKey:
          type: string
          description: |
            The tag's key
          example: Creator
        tagValue:
          type: string
          description: |
            The tag's value
          example: John Doe
  matcher:
    type: object
    description: >
      Matcher to use when checking for a successful response from a target
      group. One of 'httpCode' or 'grpcCode' is required.
    default:
      httpCode: '200'
    properties:
      httpCode:
        type: string
        description: >
          You can specify values between 200 and 499, and the default value is
          200. You can specify multiple values (for example, “200,202”) or a
          range of values (for example, “200-299”).
        default: '200'
        example: '200'
      grpcCode:
        type: string
        description: >
          You can specify values between 0 and 99. You can specify multiple
          values (for example, “0,1”) or a range of values (for example, “0-5”).
          The default value is 12.
        default: '12'
        example: '4'
