title: ITF Target Group Configuration
type: object
description: |
  Contains the configuration details of an ITF target group.
allOf:
  - $ref: ./itfTargetGroupConfigProperties.yaml
  - required:
      - vpcId
      - healthCheckPath
      - port
      - protocol
