type: object
title: Json Configuration Object
required:
  - jsonConfiguration
properties:
  jsonConfiguration:
    type: array
    description: Steps configuration for the group
    items:
      type: object
      required:
        - name
        - stepConfig
      properties:
        name:
          type: string
          description: The name of configured step
          example: stepName
        actionOnFailure:
          type: string
          description: >-
            Valid values "TERMINATE_JOB_FLOW", "TERMINATE_CLUSTER",
            "CANCEL_AND_WAIT", "CONTINUE"
          example: CONTINUE
        stepConfig:
          required:
            - jar
          type: object
          description: The JAR file used for the step.
          properties:
            args:
              type: array
              description: >-
                A list of command line arguments passed to the JAR file's main
                function when executed.
              example: '-input'
              items:
                type: string
            jar:
              type: string
              description: A path to a JAR file run during the step.
              example: emr-test
            mainClass:
              type: string
              description: The name of the main class in the specified Java file.
              example: mainClass
            properties:
              type: array
              description: A list of Java properties that are set when the step runs.
              items:
                type: object
                required:
                  - key
                  - value
                properties:
                  key:
                    type: string
                    description: The unique identifier of a key-value pair.
                    example: key
                  value:
                    type: string
                    description: The value part of the identified key.
                    example: value
