type: object
required:
  - time
  - pending
  - running
description: |
  Number of apps pending or running at a given point in time
properties:
  time:
    type: string
    format: date-time
    description: |
      Polling time
    example: '2021-11-18T17:09:37+00:00'
  pending:
    type: number
    description: |
      Number of applications that were pending at the polling time. 
    example: 0
  running:
    type: number
    description: |
      Number of applications that were running at the polling time. 
    example: 0
