type: object
required:
  - start
  - end
  - completed
  - failed
  - killed
  - timed_out
description: >
  The number of applications that ended in a given time range, grouped by the
  terminal state they reached.
properties:
  start:
    type: string
    format: date-time
    description: |
      Start of the time range
    example: '2021-11-18T17:09:37+00:00'
  end:
    type: string
    format: date-time
    description: |
      End of the time range
    example: '2021-11-18T17:09:37+00:00'
  completed:
    type: number
    description: |
      The number of apps successfully completed between >= start and < end
  failed:
    type: number
    description: |
      The number of apps that failed between >= start and < end
  killed:
    type: number
    description: |
      The number of apps killed between >= start and <end
  timedOut:
    type: number
    description: |
      The number of apps that timed-out between >= start and < end
