type: object
description: |
  The object specifying the Ocean Spark Compute configuration.
properties:
  useTaints:
    type: boolean
    default: true
    example: false
    description: >
      Enable/Disable **ocean-spark** taints on the Ocean Spark VNGs. By default,
      Spark uses taints to prevent 

      non-Spark pods to run on Ocean Spark VNGs.
  createVngs:
    type: boolean
    default: true
    example: false
    description: |
      Enable/Disable creating **ocean-spark** VNGs
