type: object
description: |
  The object specifying the Ocean Spark Spark configuration.
properties:
  appNamespaces:
    type: array
    items:
      type: string
    example:
      - spark-apps
      - spark-apps-extra-ns-1
      - spark-apps-extra-ns-2
    description: >
      List of Kubernetes namespaces that Spark applications can run in. The
      default namespace `spark-apps` is always included in the list.
