type: object
required:
  - createdAt
  - updatedAt
  - id
  - displayName
  - clusterId
  - config
allOf:
  - $ref: ./createdAtUpdatedAt.yaml
  - type: object
    description: |
      The description of a configuration template
    properties:
      id:
        $ref: ./oceanSparkConfigTemplateId.yaml
      displayName:
        $ref: ./oceanSparkConfigTemplateDisplayName.yaml
      clusterId:
        $ref: ./oceanSparkClusterId.yaml
      controllerClusterId:
        $ref: ./controllerClusterId.yaml
      config:
        $ref: ./oceanSparkApplicationSpec.yaml
