type: object
description: |
  The object specifying the Ocean Spark Ingress Controller configuration.
properties:
  managed:
    type: boolean
    default: true
    example: true
    description: >
      Should an ingress controller managed by Ocean for Apache Spark be
      installed on the cluster.
