type: object
required:
  - id
  - displayName
  - accountId
  - organizationId
  - clusterId
  - controllerClusterId
  - createdAt
  - updatedAt
description: |
  The description of an Ocean Spark job with config
properties:
  internalId:
    $ref: ./internalId.yaml
  id:
    $ref: ./oceanSparkJobId.yaml
  displayName:
    $ref: ./oceanSparkJobDisplayName.yaml
  controllerClusterId:
    $ref: ./controllerClusterId.yaml
  clusterId:
    $ref: ./oceanSparkClusterId.yaml
  createdAt:
    $ref: ./createdAt.yaml
  updatedAt:
    $ref: ./updatedAt.yaml
  config:
    $ref: ./oceanSparkApplicationSpec.yaml
