type: object
description: Computed statistics about the performance and cost of Spark applications
required:
  - cost
  - spark
properties:
  cost:
    $ref: ./oceanSparkApplicationCost.yaml
  spark:
    $ref: ./oceanSparkApplicationSparkMetrics.yaml
