type: object
description: |
  The object specifying the configuration of the Ocean Spark cluster.
properties:
  ingress:
    $ref: ./oceanSparkClusterConfigIngress.yaml
  webhook:
    $ref: ./oceanSparkClusterConfigWebhook.yaml
  compute:
    $ref: ./oceanSparkClusterConfigCompute.yaml
  logCollection:
    $ref: ./oceanSparkClusterConfigLogCollection.yaml
  spark:
    $ref: ./oceanSparkClusterConfigSpark.yaml
