type: object
description: |
  The object specifying the Ocean Spark Webhook configuration.
properties:
  useHostNetwork:
    type: boolean
    default: false
    example: true
    description: >
      Enable/Disable host networking on the Spark Operator. Host networking can
      be useful when using custom CNI plugins 

      like Calico.
  hostNetworkPorts:
    type: array
    items:
      type: integer
      example: 1234
    description: >
      List of ports allowed to use on the host network - if empty default is
      **25554**
