type: object
description: |
  The object specifying the Ocean Spark Log Collection configuration.
properties:
  collectDriverLogs:
    type: boolean
    default: true
    example: false
    deprecated: true
    description: |
      Deprecated. Use `collectAppLogs` instead, effect is the same.
  collectAppLogs:
    type: boolean
    default: true
    description: >
      Enable/Disable collecting driver and executor logs. When enabled, logs are
      stored by NetApp and can be downloaded from 

      the Spot console web interface. The logs are deleted after 30 days.
