type: object
required:
  - id
  - displayName
  - accountId
  - organizationId
  - clusterId
  - controllerClusterId
  - createdAt
  - updatedAt
description: |
  The description of an Ocean Spark job with config
properties:
  id:
    $ref: ./oceanSparkJobId.yaml
  displayName:
    $ref: ./oceanSparkJobDisplayName.yaml
  organizationId:
    $ref: ./organizationId.yaml
  accountId:
    $ref: ./accountId.yaml
  controllerClusterId:
    $ref: ./controllerClusterId.yaml
  clusterId:
    $ref: ./oceanSparkClusterId.yaml
  createdAt:
    $ref: ./createdAt.yaml
  updatedAt:
    $ref: ./updatedAt.yaml
  lastApp:
    $ref: ./oceanSparkApplication.yaml
  history:
    description: The most recent Spark applications in this job.
    type: array
    items:
      $ref: ./oceanSparkApplication.yaml
  config:
    $ref: ./oceanSparkApplicationSpec.yaml
