type: object
description: The cloud cost of the Spark application. Updated every hour
required:
  - total
  - createdAt
  - updatedAt
properties:
  createdAt:
    $ref: ./createdAt.yaml
  updatedAt:
    $ref: ./updatedAt.yaml
  total:
    type: integer
    description: The total cost of the Spark application in USD cents
    example: 0
