description: Name of connector service (value=ansible|apikeys|datadog|humio|instana|jira|opsgenie|aws_health|pagerduty|prometheus|pulumi|slack|splunk|splunk_on_call|spot|squadcast|terraform|terraform_cli|twilio|zoom)
in: path
name: service
required: true
schema:
  type: string
