openapi: "3.0.0"
info:
  version: "1.0"
  description: |
    Welcome to the Spot by NetApp OpenAPI Specification.
    Here you will find REST definitions for all Spot products and platform administration tasks.

    The API is hosted at `https://api.spotinst.io` and requires Bearer Token
    Authentication.

    For more information on how to use the Spot platform, including user guides,
    developer guides, concepts, and tutorials, see the external [Spot Documentation](https://docs.spot.io/).
  title: Spot by NetApp API
  x-logo:
    url: https://docs.spot.io/_media/images/spot.png
    altText: SpotByNetAppLogo
    href: https://docs.spot.io/api
  contact:
    email: support@spot.io
externalDocs:
  url: https://docs.spot.io/
servers:
  - url: https://api.spotinst.io
security:
  - auth: [ ]

components:
  securitySchemes:
    auth:
      $ref: commons/security.yaml#/components/securitySchemes/BearerAuth

tags: [ ]

x-tagGroups:

paths:

