openapi: "3.0.0"
info:
  description: "Spotinst API"
  version: "1.0.0"
  title: "Spot API"
  contact:
    email: "support@spot.io"
servers:
  - url: https://api.spotinst.io/
security:
  - BearerAuth: []
externalDocs:
  url: https://help.spot.io/
tags:
  - name: "Elastigroup AWS"
    description: "Elastigroup for Amazon Web Services"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-aws/
  - name: "Elastigroup Azure"
    description: "Elastigroup for Microsoft Azure"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-azure/
  - name: "Elastigroup Azure Deployment"
    description: "Deployments for Elastigroup on Microsoft Azure"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-azure/
  - name: "Elastigroup GCP"
    description: "Elastigroup for Google Cloud"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-google-cloud/
  - name: "Ocean AWS"
    description: "Ocean - Serverless containers for Amazon Web Services (AWS)"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-aws/
  - name: "Ocean ECS"
    description: "Ocean - Serverless containers for Amazon Elastic Container Service (ECS)"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-ecs/
  - name: "Ocean GKE"
    description: "Ocean - Serverless containers for for Google Kubernetes Engine"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-gke/

paths:
  #/aws/ec2/group:
  #  $ref: 'services/elastigroup/aws/paths/groups.yaml'
  #/aws/ec2/group/{groupId}:
  #  $ref: 'services/elastigroup/aws/paths/group.yaml'
  /aws/ec2/group/{groupId}/status:
    $ref: 'services/elastigroup/aws/paths/status.yaml'
  /aws/ec2/group/{groupId}/events:
    $ref: 'services/elastigroup/aws/paths/events.yaml'
  /aws/ec2/group/{groupId}/logs:
    $ref: 'services/elastigroup/aws/paths/logs.yaml'
  /aws/ec2/group/{groupId}/capacity:
    $ref: 'services/elastigroup/aws/paths/capacity.yaml'
  /aws/ec2/group/{groupId}/scale/up:
    $ref: 'services/elastigroup/aws/paths/scale-up.yaml'
  /aws/ec2/group/{groupId}/scale/down:
    $ref: 'services/elastigroup/aws/paths/scale-down.yaml'
  #/aws/ec2/group/{groupId}/scale/suspendPolicy:
  #  $ref: 'services/elastigroup/aws/paths/suspend-policy.yaml'
  #/aws/ec2/group/{groupId}/suspension:
  #  $ref: 'services/elastigroup/aws/paths/suspension.yaml'
  #/aws/ec2/group/{groupId}/scale/suspensions:
  #  $ref: 'services/elastigroup/aws/paths/suspensions.yaml'
  /aws/ec2/group/{groupId}/scale/resumePolicy:
    $ref: 'services/elastigroup/aws/paths/resume-policy.yaml'
  #/aws/potentialSavings:
  #  $ref: 'services/elastigroup/aws/paths/potential-savings.yaml'
  #/aws/instancePotentialSavings:
  #  $ref: 'services/elastigroup/aws/paths/instances-potential-savings.yaml'
  #/aws/costs:
  #  $ref: 'services/elastigroup/aws/paths/costs.yaml'
  #/aws/ec2/group/{groupId}/costs:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-costs.yaml'
  #/aws/ec2/group/{groupId}/costs/detailed:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-costs-detailed.yaml'
  #/aws/ec2/instance/{instanceId}:
  #  $ref: 'services/elastigroup/aws/paths/instance-status.yaml'
  #/aws/ec2/group/instance/import:
  #  $ref: 'services/elastigroup/aws/paths/import.yaml'
  #/aws/ec2/group/{groupId}/amiBackup:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-ami-backup.yaml'
  #/aws/ec2/group/{groupId}/instanceHealthiness:
  #  $ref: 'services/elastigroup/aws/paths/instance-healthiness.yaml'
  #/aws/ec2/group/{groupId}/detachInstances:
  #  $ref: 'services/elastigroup/aws/paths/detach-instances.yaml'
  #/aws/ec2/group/{groupId}/roll:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-deployment-status.yaml'
  #/aws/ec2/group/{groupId}/roll{rollId}:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-stop-deployment.yaml'
  #/aws/ec2/group/{groupId}/roll/{rollId}:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-deploy-status.yaml'
  #/aws/ec2/group/{groupId}/roll/{rollId}/action:
  #  $ref: 'services/elastigroup/aws/paths/elastigroup-deployment.yaml'
  #/aws/ec2/group/autoScalingGroup/import:
  #  $ref: 'services/elastigroup/aws/paths/import-asg.yaml'
  #/aws/ec2/spotType:
  #  $ref: 'services/elastigroup/aws/paths/get-instance-by-region.yaml'
  #/aws/ec2/instanceTypeRecommendation:
  #  $ref: 'services/elastigroup/aws/paths/suggested-instance-type.yaml'
  #/aws/ec2/instance/interruption:
  #  $ref: 'services/elastigroup/aws/paths/instance-interruption.yaml'
  #/aws/ec2/instance/signal:
  #  $ref: 'services/elastigroup/aws/paths/instance-signal.yaml'
  #/aws/ec2/instance/{instanceId}/lock:
  #  $ref: 'services/elastigroup/aws/paths/instance-lock.yaml'
  #/aws/ec2/instance/{instanceId}/unlock:
  #  $ref: 'services/elastigroup/aws/paths/instance-unlock.yaml'
  #/aws/ec2/instance/{instanceId}/standby/enter:
  #  $ref: 'services/elastigroup/aws/paths/instance-standby.yaml'
  #/aws/ec2/instance/{instanceId}/standby/exit:
  #  $ref: 'services/elastigroup/aws/paths/instance-exit-standby.yaml'
  #/mcs/kubernetes/cluster/{clusterIdentifier}/costs:
  #  $ref: 'services/ocean/aws/path/kubernetes-cluster-costs.yaml'
  /compute/azure/group:
    $ref: 'services/elastigroup/azure/paths/groups.yaml'
  /compute/azure/group/{groupId}:
    $ref: 'services/elastigroup/azure/paths/group.yaml'
  /compute/azure/group/{groupId}/status:
    $ref: 'services/elastigroup/azure/paths/group-status.yaml'
  /compute/azure/group/{groupId}/detachInstances:
    $ref: 'services/elastigroup/azure/paths/group-detach.yaml'
  /compute/azure/group/{groupId}/roll:
    $ref: 'services/elastigroup/azure/paths/group-deployments.yaml'
  /compute/azure/group/{groupId}/roll/{deploymentId}:
    $ref: 'services/elastigroup/azure/paths/group-deployment.yaml'
  /compute/azure/task:
    $ref: 'services/elastigroup/azure/paths/tasks.yaml'
  /compute/azure/task/{taskId}:
    $ref: 'services/elastigroup/azure/paths/task.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: 'commons/security.yaml#/components/securitySchemes/BearerAuth'
