openapi: "3.0.0"
info:
  description: "Spotinst API"
  version: "1.0.0"
  title: "Spot API"
  contact:
    email: "support@spot.io"
servers:
  - url: https://api.spotinst.io/
security:
  - BearerAuth: []
externalDocs:
  url: https://help.spot.io/
tags:
  - name: "Elastigroup AWS"
    description: "Elastigroup for Amazon Web Services"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-aws/
  - name: "Elastigroup Azure"
    description: "Elastigroup for Microsoft Azure"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-azure/
  - name: "Elastigroup Azure Deployment"
    description: "Deployments for Elastigroup on Microsoft Azure"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-azure/
  - name: "Elastigroup GCP"
    description: "Elastigroup for Google Cloud"
    externalDocs:
      url: https://help.spot.io/elastigroup-for-google-cloud/
  - name: "Ocean AWS"
    description: "Ocean - Serverless containers for Amazon Web Services (AWS)"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-aws/
  - name: "Ocean ECS"
    description: "Ocean - Serverless containers for Amazon Elastic Container Service (ECS)"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-ecs/
  - name: "Ocean GKE"
    description: "Ocean - Serverless containers for for Google Kubernetes Engine"
    externalDocs:
      url: https://help.spot.io/spotinst-api/ocean/ocean-cloud-api/ocean-for-gke/

paths:
  /aws/ec2/group:
    $ref: 'services/elastigroup/aws/paths/groups.yaml'
  /aws/ec2/group/{groupId}:
    $ref: 'services/elastigroup/aws/paths/group.yaml'
  /compute/azure/group:
    $ref: 'services/elastigroup/azure/paths/groups.yaml'
  /compute/azure/group/{groupId}:
    $ref: 'services/elastigroup/azure/paths/group.yaml'
  /compute/azure/group/{groupId}/status:
    $ref: 'services/elastigroup/azure/paths/group-status.yaml'
  /compute/azure/group/{groupId}/detachInstances:
    $ref: 'services/elastigroup/azure/paths/group-detach.yaml'
  /compute/azure/group/{groupId}/roll:
    $ref: 'services/elastigroup/azure/paths/group-deployments.yaml'
  /compute/azure/group/{groupId}/roll/{deploymentId}:
    $ref: 'services/elastigroup/azure/paths/group-deployment.yaml'
  /compute/azure/task:
    $ref: 'services/elastigroup/azure/paths/tasks.yaml'
  /compute/azure/task/{taskId}:
    $ref: 'services/elastigroup/azure/paths/task.yaml'
  /gcp/gce/group:
    $ref: 'services/elastigroup/gcp/paths/groups.yaml'
  /gcp/gce/group/{groupId}:
    $ref: 'services/elastigroup/gcp/paths/group.yaml'
  /gcp/gce/group/gke/import:
    $ref: 'services/elastigroup/gcp/paths/gke-import.yaml'
  /gcp/gce/group/{groupId}/status:
    $ref: 'services/elastigroup/gcp/paths/group-status.yaml'
  /gcp/gce/group/{groupId}/events:
    $ref: 'services/elastigroup/gcp/paths/group-event.yaml'
  /gcp/gce/group/{groupId}/log:
    $ref: 'services/elastigroup/gcp/paths/group-elastilog.yaml'
  /gcp/gce/group/{groupId}/scale/up:
    $ref: 'services/elastigroup/gcp/paths/group-scale-up.yaml'
  /gcp/gce/group/{groupId}/scale/down:
    $ref: 'services/elastigroup/gcp/paths/group-scale-down.yaml'
  /gcp/gce/group/{groupId}/costs:
    $ref: 'services/elastigroup/gcp/paths/group-costs.yaml'
  /gcp/gce/group/{groupId}/roll:
    $ref: 'services/elastigroup/gcp/paths/group-rolls.yaml'
  /gcp/gce/group/{groupId}/roll/{rollId}:
    $ref: 'services/elastigroup/gcp/paths/group-roll.yaml'
  /gcp/gce/group/{groupId}/deatchInstances:
    $ref: 'services/elastigroup/gcp/paths/group-detach-instances.yaml'
  /gcp/gce/instance/{instanceId}:
    $ref: 'services/elastigroup/gcp/paths/instance-status.yaml'
  /gcp/gce/instance/{instanceId}/lock:
    $ref: 'services/elastigroup/gcp/paths/instance-lock.yaml'
  /gcp/gce/instance/{instanceId}/unlock:
    $ref: 'services/elastigroup/gcp/paths/instance-unlock.yaml'
components:
  securitySchemes:
    BearerAuth:
      $ref: 'commons/security.yaml#/components/securitySchemes/BearerAuth'
