name: Bundle and Deploy

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*.*"

jobs:
  bundle-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Bundle
        run: |
          yarn install
          yarn bundle

      - name: Deploy Local
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build

      - name: Deploy Upstream
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: spotinst/docs
          BRANCH: gh-pages
          FOLDER: build
          TARGET_FOLDER: api
          CLEAN: false
