name: Validate and Bundle

on:
  pull_request:
    branches:
      - master

jobs:
  validate-and-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Validate
        run: |
          yarn install
          yarn validate
          yarn bundle
