name: Validate

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install and Validate
        run: |
          yarn install
          yarn validate
          yarn bundle:redocly
          yarn bundle:swagger

      - name: redoc-lint
        uses: mhiew/redoc-lint-github-action@v3
        with:
          args: 'api/spot.yaml'
